### ISSUE TITLE
Add push/pull only sync config

### ISSUE THREAD

**Issue by ellie** [ellie/atuin#102]
Add two options to the client config file:

eg
```
sync_push = false
sync_pull = true
```

This would be useful on work computers where sharing shell history would be against corporate policy, but being able to download your history from personal devices would be useful

**Comment by WladyX** [comment]
Hey @ellie, 
Was this implemented? I don't see it in the config
Thank you!
Vlad

**Comment by ellie** [comment]
It was not, and is unlikely to be something we put any work behind any time soon

**Comment by WladyX** [comment]
ok, cool, thanks for the fast reply and thank you for sharing this awesome work!
