### ISSUE TITLE
bug: `atuin search -i` unexpected  behaviour

### ISSUE THREAD

**Issue by 17307** [ellie/atuin#1020]
version: v15.0.0 
After selecting a history using the interactive search, it will be printed under `atuin search -i` instead of executing this command.

![image](https://github.com/ellie/atuin/assets/26533008/600110ae-32fb-4d89-aa90-0408da401af7)

Instead of executing the history command after hitting enter, the next line of `atuin search -i` is printed out.

![image](https://github.com/ellie/atuin/assets/26533008/ce60555c-0706-46cd-891d-2b7a5432c737)

**Comment by conradludgate** [comment]
This is working as intended, we can't execute a command or write to your prompt without our init script configured appropriately

**Comment by 17307** [comment]
> This is working as intended, we can't execute a command or write to your prompt without our init script configured appropriately

I have'd configured `eval "$(atuin init zsh --disable-up-arrow)"` in my .zshrc file.

**Comment by HoffsMH** [comment]
> This is working as intended, we can't execute a command or write to your prompt without our init script configured appropriately

That would be fine if something like this would work.

```zsh
my_custom_history_command() {
  print -z "$(atuin search -i)"
}
```

Is there any recipe or otherwise noted anywhere in the documentation we can use atuin search -i as a command or alias or shell function to fill out our prompt from a command rather than a keybind?
