### ISSUE TITLE
Are there instructions to use atuin with alternative shells ? (xonsh)

### ISSUE THREAD

**Issue by StitiFatah** [ellie/atuin#1027]
Hey, 

Have been using atuin with zsh for a couple of months, I must say it's a very convenient piece of software, thanks for that, I'm know trying out the `xonsh` shell and was wondering if there were generic instructions for shells that don't have an `atuin init $SHELL`

Thanks in advance

**Comment by rirze** [comment]
Looking for something similar with ion-shell

**Comment by ellie** [comment]
Hey! There are not, as it varies significantly by shell + depends on the hooks available. If we had instructions, we would just implement the shell plugin and include it

**Comment by rirze** [comment]
Are there any guidelines? I'd love to open a PR with support if there was some documentation for what needs to be minimally implemented.

**Comment by patricksjackson** [comment]
The best way to understand what's necessary would be to look at the most recent shell support PR, #788

New shells are implemented by writing an import module to convert the existing history from the shell, see the others [here](https://github.com/ellie/atuin/tree/main/atuin-client/src/import). 

And writing shell hooks scripts, [existing ones here](https://github.com/ellie/atuin/tree/main/atuin/src/shell). These scripts are what atuin uses for `atuin init <shell>`. Not all shells support the hooks necessary for atuin though. `nushell`, for example, didn't support the necessary hooks and actually needed them added before atuin could be supported.

Looking at their docs I don't think `ion-shell` supports any hooks at all, which means it's not possible to integrate with atuin.

I was confused by the `xonsh` docs, so I can't tell if that supports hooks. You'd need to ask them.

**Comment by Matthieu-LAURENT39** [comment]
Did this ever get implemented?
Looking into using atuin with xonsh as well

**Comment by arcuru** [comment]
Nothing has been done in Atuin.

Taking a second look, this can definitely be implemented using Events in xonsh: https://xon.sh/tutorial_events.html. They do support the necessary hooks that Atuin would need, `on_precommand()` and `on_postcommand()`.

If you're familiar with xonsh I expect it would be fairly easy if you'd like to implement it. I've been trying out some different shells lately and had been meaning to checkout xonsh, so I may get to it myself at some point.

**Comment by Matthieu-LAURENT39** [comment]
I was thinking of implementing it, i just wanted to check if it was done already to not reinvent the wheel.
I'll try to make a PR this weekend.

**Comment by arcuru** [comment]
Awesome! If you have any questions, the Atuin discord is fairly active and would be happy to help from the Atuin side :)
