### ISSUE TITLE
Only use space above the cursor when opening Atuin

### ISSUE THREAD

**Issue by PMunch** [ellie/atuin#1070]
Triggering Atuin in a fresh shell (or one with only a few commands) is a bit visually disturbing. My eyes now have to jump from the command input where I was just looking, down to the bottom of the terminal window, and then back up to the command input when I've selected something. It would be nice if Atuin tried to minimise the amount of such focus bounce. When using normal history and just hitting up the command appears right where I'm looking, making it very easy to quickly go back and pick what I needed (although not with the nice search and context Atuin provides). This also applies to a full terminal, hitting up means my eyes now have to switch from the end of my PS1 back to near the beginning of the previous line. If you're in a deep folder structure on a wide monitor this can be a bit jarring.

Overall I really like it though, but I feel like this focus bouncing could become the thing that makes me switch back..

**Comment by conradludgate** [comment]
You might be interested in trying out our "inline mode". I believe in the config it's called inline_height. If you set it to ~20 it'll draw the search box below the prompt, leaving the search bar close to the prompt

**Comment by PMunch** [comment]
Hmm, that does bring it closer, at least it's an improvement. Come to think of it I might just disable the Atuin search interface for up, and then only bring it up with Ctrl+r and replace my `history | grep` workflow with Atuin search instead.
