### ISSUE TITLE
Debugging zsh 10+ sec startup?

### ISSUE THREAD

**Issue by aronchick** [ellie/atuin#1071]
I'm noticing about 10s startup since adding Atuin on a M1 Mac with 16 GB of RAM.

Zprof reports the following:
```
 1)    1          10.63    10.63   46.90%     10.63    10.63   46.90%  _atuin_preexec
```

I don't have a terribly large history (i don't think) - 603k. Any suggestions on narrowing down or speeding startup? (or pushing loading to be lazy?)

**Comment by norpol** [comment]
Put a `set -x` on top and `set +x` in the end of your `~/.zshrc` and you'll see where you are stuck exactly. I have a massive history so that shouldn't be a startup issue.

**Comment by conradludgate** [comment]
I also think it shouldn't be an issue. We use libsqlite which lazy loads the database if it needs to, so it should be very efficient. 

There are some known problems using sqlite on some filesystems though. I don't recall which right now, but this might be worth looking into

**Comment by ellie** [comment]
There can be issues with some ZFS systems (all SQLite databases have it), wrt latencies

Same with network filesystems

**Comment by aronchick** [comment]
LOL.

Looking at my `.zshrc` I found the following command:

```
echo 'eval "$(atuin init zsh)"' >> ~/.zshrc
```

I also found about 75 `eval "$(atuin init zsh)"`.

Safe to say this was the problem.
