### ISSUE TITLE
some history command stuck on the latest command by having "0s ago" timestamp

### ISSUE THREAD

**Issue by KUD-00** [ellie/atuin#1072]
I encounted this problem this month i think. I don't know if it is a bug or ...feature, its' annoying.

![image](https://github.com/ellie/atuin/assets/70764075/5b64b86d-08aa-41bb-bd7f-bdf056938589)

**Comment by tpiekarski** [comment]
I got the same issue on Ubuntu 23.04 running atuin 12.0.0 (installed most recent version from Ubuntu package repository). A few commands stuck with 0s at the bottom.

To keep using atuin I had to remove the database .local/share/atuin and rerun an `atuin import bash`. 
It does import the commands in a rather strange order, at first sight it seems to be alphabetically.

And I am aware that there is a more recent version, and especially one which offers a way to delete commands from history. But I'd like to keep using the version offered by distribution vendor for being able to update it with apt, like all other packages.

@KUD-00 With what distribution and version did you run into this issue? Is it for you an option to install >= 14.0.0 and try to delete those stuck commands with something like `atuin search --delete ...` See https://atuin.sh/blog/release-v14 for more details.

**Comment by conradludgate** [comment]
We mark items as "0s" ago if they somehow occurred in the future. We had issues with DST before but I'll take another look through later to see how were recording datetimes

**Comment by tpiekarski** [comment]
@conradludgate Thanks, that figures. I was developing a time-based feature in my companies product and needed to set my date into the future for testing. Guess I have run a few commands and forgot to switch the time back. The workaround I assume should then be an update to at least 14.0.0 and remove those stuck commands from history.

**Comment by KUD-00** [comment]
that make sense. I got dual boot on my pc and the hardware time in Linux appears weird. that caused this 0s ago problem.
thank you for your responses.
