### ISSUE TITLE
Some way to embed atuin permanently in shells

### ISSUE THREAD

**Issue by luke-jr** [ellie/atuin#1081]
Attackers typically have to use available installed shells at least temporarily before they setup their rootkit. At least some know to disable shell history, and even custom shell history extensions. It would be nice if there was a way to patch my shells to embed atuin so it cannot be simply turned off (similar to the "bashlogger" patch available in Gentoo).

**Comment by conradludgate** [comment]
This is a neat idea but I don't think we're going to prioritise this workflow for the time being.

Thanks for the interest. We are hoping to make more of the atuin code pluggable in future so that third parties can integrate directly with it to make custom tooling like this
