### ISSUE TITLE
Append-only mode for server

### ISSUE THREAD

**Issue by luke-jr** [ellie/atuin#1082]
It would be nice to configure the server to only allow adding history, not deleting or modifying. Combined with #1081, this could help ensure an attacker's initial actions are logged and beyond their ability to delete (provided the server isn't also compromised).

**Comment by conradludgate** [comment]
It currently is append only. We provide soft deletes only because the sync expects a linear history.

Our status API also returns all IDs which have been deleted, so I guess you could use that to detect attempts to clean up
