### ISSUE TITLE
Gitpod with Atuin Blog Post - Any chance for a review? 🤝 

### ISSUE THREAD

**Issue by loujaybee** [ellie/atuin#1090]
👋 Hey folks. 

**Context:** I work for gitpod.io, we are a [Cloud Development Environment](https://www.gitpod.io/cde) company, to allow developers, teams and companies to code in cloud-based workspaces. Gitpod makes it quite easy to create new workspaces, so we often see developers making as many as 10-20 a day, so they are quite ephemeral. We have now had a long-standing issue related to improving the state of terminal history in Gitpod [https://github.com/gitpod-io/gitpod/issues/9019](https://github.com/gitpod-io/gitpod/issues/9019) and are looking into options. Our first step was to really review what exists out there as a 3rd party that we can encourage our users to use, which is how we discovered Atuin. 

Since users can use [dotfiles](https://www.gitpod.io/docs/configure/user-settings/dotfiles#dotfiles), they can pretty much install whatever they want into a workspace which makes integrating Atuin quite easy. So, I decided to [write up a short guide](https://github.com/gitpod-io/website/pull/3826) for our website of using Gitpod + Atuin ([you can see the preview here](https://deploy-preview-3826--gitpod-kumquat.netlify.app/guides/persisted-terminal-history-atuin)). I appreciate (as always) that time is short but if you are able to give the post a quick review, for any mistakes, or key features of Atuin that you think we should be highlighting, that would be much appreciated. Gitpod has quite a big community, so I'd hope this would introduce some new folks to Atuin ! 🚀 

If there's anything we can do for you or the project, let me know ! 

(feel free to close the issue when you've seen, or if you're too short of right now 🙏)

**Comment by ellie** [comment]
Hey! I hadn't considered the CDE usecase, but it totally makes sense! The post looks good to me, I've dropped a couple of minor comments in a review on your PR.

> If there's anything we can do for you or the project, let me know !

If you have time I'd love to discuss the possibility of further integration with GitPod! We could definitely make the setup process smooth + painless for your users. Fwiw, we will be announcing some plans to take Atuin much further soon.

> Gitpod has quite a big community, so I'd hope this would introduce some new folks to Atuin ! 🚀

Thank you so much for this! 💖 🐢

**Comment by loujaybee** [comment]
> Hey! I hadn't considered the CDE usecase, but it totally makes sense! The post looks good to me, I've dropped a couple of minor comments in a review on your PR.

Indeed, it definitely makes a lot of sense. Happy to chat more about the market, it's growing quite a lot right now. This [recent thread](https://twitter.com/GergelyOrosz/status/1667448993176059905?s=20) from Gergely Orosz is also quite nice. 

> We could definitely make the setup process smooth + painless for your users. Fwiw, we will be announcing some plans to take Atuin much further soon.

👀 Very exciting ! I'm curious to see the response from the community 😁 Self-hosted Atuin could be interesting for our [Dedicated](https://www.gitpod.io/dedicated) customers (Gitpod, but hosted in our customers' cloud account), who have some security, networking, compliance or other requirements they need to satisfy... 

> If you have time I'd love to discuss the possibility of further integration with GitPod! 

For sure — `louis@gitpod.io` or just [throw something in my calendar](https://calendly.com/lou-gitpod/chat) 🙏

**Comment by ellie** [comment]
I've put something in your calendar! Looking forward to talking more 🙏

**Comment by loujaybee** [comment]
🚀 https://www.gitpod.io/guides/persisted-terminal-history-atuin
