### ISSUE TITLE
Default OS X `db_path` does not match the comment in default `config.toml`

### ISSUE THREAD

**Issue by simon-b** [ellie/atuin#1091]
According to the default `config.toml`, on mac the default database will be stored in your "system data directory":
`~/Library/Application Support/com.elliehuxtable.atuin/history.db`
In this default config `db_path` is not set (only a comment), so one would expect to find the db located in this default location.

However, on my mac this is not true; with `db_path` unset, as per default config, I can see that the db is here: `~/.local/share/atuin/history.db`.
According to the default `config.toml` this is the default Linux location, but for me it's also where I find it on mac.

**Comment by simon-b** [comment]
Quick look and it seems that this was old behaviour:

https://github.com/ellie/atuin/commit/156893d7#diff-40a913e7519b21e144292a549971f0c8c3cc3ed149336446de8a4fbed16ce07fL93
removed in favour of always using `data_dir()`

No longer correct/relevant in the toml file, then?

**Comment by ellie** [comment]
You're correct! The config file defaults need updating
