### ISSUE TITLE
See history for only commands issued in a directory (or subdirectories)

### ISSUE THREAD

**Issue by bizzguy** [ellie/atuin#116]
I do Android development and electron development.  The history for each is entirely independent.  It would be useful when I'm in the directory where I do Android development to only see the commands related to Android.  And similarly for when I'm working in the electron directory.  

Maybe this could be accomplished with a command flag or a dot file in the directory or parent directories.

**Comment by conradludgate** [comment]
Currently you can do `atuin search -i --cwd .` to manually search for only the current directory

A simple addition could be 'repo mode'. If enabled, and you're in a git repository, it could show only commands from that repository. What do you think @ellie?

**Comment by conradludgate** [comment]
Admittedly I'm not sure about that solution either. It's hard to add these search features without being restrictive in another way 🤔

**Comment by ellie** [comment]
I'd like to avoid adding loads of modes as it might get a little too complicated 

As @bizzguy suggests, a .atuin.toml file could be automatically loaded per directory, if present, and override the current config. 

We could then have an attribute in the config such as 

`search_command=atuin search -i --cwd .` 

Or similar 

Alternatively this could be configured via an environment variable, and then something like direnv could be used. Considering it's more a shell config than an Atuin config, this approach might be better!

**Comment by bizzguy** [comment]
I like @ellie 's idea.  Although, not sure I would want an extra file generated in every directory I use.  What about creating the file  in the user's home.  I would tend to want the changes in config to apply to all my usages.

**Comment by ellie** [comment]
@bizzyguy just to clarify there! They wouldn't be generated, the user can create them in a directory if they wish to override any settings

I'd like to add a key binding to switch between global/directory/session search too :)

**Comment by ellie** [comment]
I think this is largely covered by #118, so I'm going to close it. Please let me know if this is not the case :)

**Comment by ellie** [comment]
also see #20
