### ISSUE TITLE
Make C-r closer to stock

### ISSUE THREAD

**Issue by quentinmit** [ellie/atuin#122]
When atuin is launched by `C-r`, it treats the pattern as a shell glob, which means (absent any globs) it performs a prefix match on the history. The shell's default `C-r` behavior meanwhile is a substring match, so e.g. `C-r debug` would match `make debug` in bash, but not in atuin.

To make atuin's behavior closer to the shell's normal behavior, I'd like to suggest that an implicit `*` be prepended to the pattern iff the pattern doesn't contain any shell globs. This is also similar to how the shell's stock `C-r` behavior is case-insensitive unless the pattern contains an uppercase character.

**Comment by ellie** [comment]
At the moment you can put

`search_mode="fulltext"`

into the config file! See https://github.com/ellie/atuin/blob/main/docs/config.md#search_mode (this was added with #75)

However I would be up for making this the default.

**Comment by quentinmit** [comment]
I think I'm advocating for a third option, "auto", where the behavior changes depending on whether the pattern contains glob characters.

**Comment by ellie** [comment]
Resolved

**Comment by quentinmit** [comment]
If this is resolved, what is the configuration option for this? I don't see this documented as a `search_mode` yet. Thanks!

**Comment by ellie** [comment]
> C-r debug would match make debug in bash, but not in atuin

This is implemented with `search_mode = 'fuzzy'`, which I believe would match your request quite nicely

**Comment by quentinmit** [comment]
> > C-r debug would match make debug in bash, but not in atuin
> 
> This is implemented with `search_mode = 'fuzzy'`, which I believe would match your request quite nicely

It looks to me like `search_mode = 'fuzzy'` requires a leading `^` to trigger a prefix match. And my (admittedly pre-`fuzzy`) build doesn't appear to recognize `^A` or the arrow keys to navigate the search string, so this means that you have to choose the type of match before typing the search string. (And conversely if you want to do a suffix match you have to type the `$` last, which means you have to keep typing and deleting it if you want to see partial matches as you type.) To me that seems like fundamentally different semantics from what I suggested here. My use case is something like `^Rssh`, "oh that's finding a bunch of `git --ssh` invocations", type a `*` and it instantly switches to only showing commands that start with `ssh`.
