### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by iquiw** [ellie/atuin#135]
First of all, Atuin solved annoyances of bash history for me. Thank you so much!

Slightly related to #84, but I want to use Atuin with MSYS2 bash on Windows.

I tried to build Atuin with the following changes and it works fine on Windows Terminal.

* Use local termion with [termion MR!174 - Add Windows 10 support](https://gitlab.redox-os.org/redox-os/termion/-/merge_requests/174) through `[patch.crates-io]`.
* Disable `server` command at all.

Unfortunately, it is not clear when/whether the MR is merged.
I think another option is to switch [crossterm](https://github.com/crossterm-rs/crossterm) which already supports Windows. But it requires some code changes.

**Comment by ellie** [comment]
> First of all, Atuin solved annoyances of bash history for me. Thank you so much!

Glad you like it! :blush: 

Sure, I don't see why we can't do this. I know it's different, but have you tried with WSL? I'm mostly interested in whether or not it works haha, I haven't yet had a chance to try.

I think wrt the termion change, I'd rather we have a go switching to crossterm. Using tui-rs we should be able to change backend, and hopefully we aren't using any/too many termion specific features so the switch could be pretty smooth. 

May I ask what was up with the server + why it needed disabling?

In any case I'm totally up for supporting Windows, though I haven't worked on anything for Windows in a *long* time so would prefer someone make a PR :joy: 

Thanks for having a go at this anyway, really appreciate the work :)

**Comment by iquiw** [comment]
> Sure, I don't see why we can't do this. I know it's different, but have you tried with WSL? I'm mostly interested in whether or not it works haha, I haven't yet had a chance to try.

I'm not using WSL(2) as I'd like to work on Windows filesystem and WSL2 is known to be slow in the case.
I think there is no problem to run Atuin with WSL.

> May I ask what was up with the server + why it needed disabling?

`fork`  crate failed to be built.
And as I am not using `server` command right now, I just chose the fastest way to build Atuin.

> In any case I'm totally up for supporting Windows, though I haven't worked on anything for Windows in a long time so would prefer someone make a PR 😂

OK, I will try crossterm and get back.

Thanks!

**Comment by iquiw** [comment]
Trying crossterm.

I found crossterm's `EnableAlternateScreen`/`LeaveAlternateScreen` does not work well on MSYS2 bash, which seems to use Win32 API instead of ANSI escape sequence. Displayed texts are sometimes not cleared and selected command is displayed above prompt.
I am checking this further...

Besides that, it seems most different part is `termion::event::Key` to `crossterm::event::KeyEvent` change.

```rust
        Key::Esc | Key::Ctrl('c') | Key::Ctrl('d') | Key::Ctrl('g') => {
            return Some(String::from(""))
        }
```
to be
```rust
        KeyEvent {
            code: KeyCode::Esc, ..
        }
        | KeyEvent {
            code: KeyCode::Char('c'),
            modifiers: KeyModifiers::CONTROL,
        }
        | KeyEvent {
            code: KeyCode::Char('d'),
            modifiers: KeyModifiers::CONTROL,
        }
        | KeyEvent {
            code: KeyCode::Char('g'),
            modifiers: KeyModifiers::CONTROL,
        } => return Some(String::from("")),
```

**Comment by iquiw** [comment]
> I found crossterm's `EnableAlternateScreen`/`LeaveAlternateScreen` does not work well on MSYS2 bash

Found it is caused by `crossterm::terminal::enable_raw_mode` instead.
There are several issues reported in `crossterm` repo related Windows (Terminal), checking them.

**Comment by iquiw** [comment]
OK, I found what's going on.

On Windows, `crossterm` checks whether the environment supports ANSI escape sequences by
(1) `TERM` environment variable is set and not `dumb`.
or
(2) The console input can set `ENABLE_VIRTUAL_TERMINAL_PROCESSING` mode.
To execute (2) is required to make escape sequences work, but it is not executed if `TERM` is set.
Ref. [ansi_support.rs](https://github.com/crossterm-rs/crossterm/blob/b31782249e3ef1c2e5d8f2f668763fddb2e0a060/src/ansi_support.rs#L41-L42)

I won't write `crossterm` specific issues here any more as it is not Atuin's problem. Sorry for the noises.

**Comment by ellie** [comment]
I'm going to close this one for now, Windows isn't really something we can support unfortunately

**Comment by iquiw** [comment]
OK, thank you for the consideration.

**Comment by Magniquick** [comment]
commenting this here as this is still the first result when searching for atuin windows
I made a [gh action](https://github.com/Magniquick/atuin-win/actions) that builds atuin on msys2 and throws out the binary as a release artifact
Needless to say, use at your own risk - this is something I cooked up within an hour or so.

**Comment by Esgariot** [comment]
I've iterated upon what @Magniquick has done and created https://github.com/Esgariot/atuin-win . It's building `atuin` from release assets.

I have also created https://github.com/Esgariot/scoop-bucket which contains manifest for atuin

**Comment by gigberg** [comment]
tks @Esgariot , and atuin on git bash now support login and sync, another thing need to do  is downloading `bash-preexec.sh` manually.

note: scoop not install `atuin-update` command like linux, so use `scoop update atuin` to do an update.

see as https://setup.atuin.sh/
```bash
if ! grep -q "atuin init bash" ~/.bashrc; then
  curl https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh -o ~/.bash-preexec.sh
  printf '\n[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh\n' >> ~/.bashrc
  echo 'eval "$(atuin init bash)"' >> ~/.bashrc
fi
```

**Comment by ltrzesniewski** [comment]
I'm leaving this message here in case it could be useful:

**Atuin now supports [PowerShell on Windows](https://docs.atuin.sh/cli/guide/installation/#on-windows) natively** (although on a tier 2 level).

```powershell
winget install -e Atuinsh.Atuin
if (-not (Test-Path -Path $PROFILE)) { New-Item -ItemType File -Path $PROFILE -Force | Out-Null }
Write-Output 'atuin init powershell | Out-String | Invoke-Expression' >> $PROFILE
```

You can find the Windows Atuin binary on WinGet or in the GitHub releases.

**Comment by God-damnit-all** [comment]
> (although on a tier 2 level)

Sorry, but what does `tier 2 support` even mean?

**Comment by ltrzesniewski** [comment]
@God-damnit-all https://github.com/atuinsh/atuin/pull/2966#issuecomment-3469782075
