### ISSUE TITLE
Cant Sync with the Server and other Errors 

### ISSUE THREAD

**Issue by neerajbadlani** [ellie/atuin#145]
You are already logged in! Please run 'atuin logout' if you wish to login again
[master:.configfiles] atuin key
Error: invalid type: integer `120`, expected Key

Location:
    atuin-client/src/encryption.rs:79:61

**Comment by conradludgate** [comment]
There's not a lot to go off of here. 2 outcomes.

I'm trying to work on getting more significant backtraces for atuin.
We should have an `atuin config dump` that shows how atuin is currently seeing your environment so we can better audit these kinds of bugs

**Comment by ellie** [comment]
Closed due to lack of further info

I wonder if this is also due to the sync performance issues we've had reported in the past. Scaling the database up has kept those at bay so far, and I'd like to address sync performance in the next (v0.9.0 probs) release.
