### ISSUE TITLE
`_atuin_search_widget` suddenly stopped working

### ISSUE THREAD

**Issue by Vapourium** [ellie/atuin#147]
`_atuin_search_widget` doesn't appear when I call `eval "$(atuin init zsh)"`.  
Among other things, `atuin search` and most `atuin history` commands don't work.  
Here's a sneak peak of what I get: 
![image](https://user-images.githubusercontent.com/34890978/121536217-de9ace80-c9d0-11eb-81d0-c2a9f5d6d4a9.png)

**Comment by DanKGooGLy** [comment]
And this is what I get when I hit ctrl + r, even though I binded it to atuin: 
![image](https://user-images.githubusercontent.com/34890978/121536363-fd00ca00-c9d0-11eb-9ead-455dccebd9a1.png)

**Comment by ellie** [comment]
This sometimes happens because of a terminal mode change. If you could do "ctrl-v, up arrow" and share the result :)

If you check the source and see what we've bound the widget to, I suspect this will not match what you see

**Comment by Vapourium** [comment]
Sorry about this, but I've switched machines and fixed the issue since. Must've forgotten about this issue.
