### ISSUE TITLE
Unable to load with antigen: "Error! Activate logging and try again."

### ISSUE THREAD

**Issue by Dentrax** [ellie/atuin#148]
Thanks for great tool! I was trying to install with `antigen`, with the following script:

```
source /usr/local/share/antigen/antigen.zsh

antigen use prezto

antigen bundles <<EOB
    ellie/atuin
EOB

antigen apply
```

And it throws `Installing ellie/atuin... Error! Activate logging and try again.` error once I do `source` the shell. Any ideas? 🤔

**Comment by conradludgate** [comment]
I think this is solved, I'll close for now
