### ISSUE TITLE
`atuin import auto` doesn't autodetect bash

### ISSUE THREAD

**Issue by vincentdephily** [ellie/atuin#168]
# Observed

```
$ echo $SHELL
/bin/bash
$ atuin import auto
        Atuin
======================
          🌍
       🐘🐘🐘🐘
          🐢
======================
Importing history...
cannot import /bin/bash history
$ atuin import bash
        Atuin
======================
          🌍
       🐘🐘🐘🐘
          🐢
======================
Importing history...
Importing history from bash
Import complete!
$
```

# Expected

`atuin import auto`  should manage to autodetect bash from the `SHELL` env or similar.

**Comment by llagerlof** [comment]
`$ atuin import bash` did the trick. Thanks @vincentdephily.

But yes, `auto` isn't working for bash in my system, and the $SHELL is pointing to `/bin/bash`.

**Comment by ellie** [comment]
Resolved in https://github.com/ellie/atuin/pull/352
