### ISSUE TITLE
Mention the Alt-<n> shortcut in the documentation

### ISSUE THREAD

**Issue by rob-smallshire** [ellie/atuin#172]
Otherwise it's not obvious how to access these shortcuts.

**Comment by rob-smallshire** [comment]
Found it in the docs!

**Comment by jucor** [comment]
@rob-smallshire where in the doc please? I'm looking for it too :)

**Comment by ellie** [comment]
Hey @jucor! It's just at the top of our README, not very prominent so could do with adjusting. Alt-<n> allows you jump to the index numbers displayed on the left of the search UI

**Comment by ellie** [comment]
> Ah thanks @ellie ! Saw it -- I was looking in the documentation website, not the README. At some point I hit another key combination that allowed to switch between Globa/Host/something else, but I don't remember which, and again can't find it. Not likely to use this specific one much yet at this stage, though.

Ahh thanks for highlighting that! We totally need to improve the docs there, the website is super new!

Ctrl-r will cycle the filter modes 😁
