### ISSUE TITLE
Removing current directory throws errors

### ISSUE THREAD

**Issue by chelmertz** [ellie/atuin#174]
Minimal steps to reproduce:

```
mkdir /tmp/atuin-test
cd !$
rm -rf /tmp/atuin-test
```

Now, the same error message is written for every interaction with the shell (like, typing `ls`):

```
Error: No such file or directory (os error 2)

Location:
    atuin-client/src/settings.rs:138:74
```

Even if I create the same directory again, the error message gets written.

Version:
```
$ cargo install --list
atuin v0.7.1 (https://github.com/ellie/atuin.git?rev=0b9dc6696be#0b9dc669):
    atuin
```

**Comment by conradludgate** [comment]
Discussion continued in #195
