### ISSUE TITLE
fuzzy match reordering by shortness of span

### ISSUE THREAD

**Issue by mwotton** [ellie/atuin#177]
I've noticed that using atuin with the fuzzy matcher, i'll often match something recent that isn't very helpful, just because it has the right letters spread over a larger command that's more recent than the command that was arguably a better match (by virtue of compactness).

I have an experimental post-processor built that seems to work: would you be interested in a PR, or should i maintain a fork?

**Comment by ellie** [comment]
Definitely interested in a PR! Thanks for raising this 😁
