### ISSUE TITLE
collapse identical adjacent commands?

### ISSUE THREAD

**Issue by mwotton** [ellie/atuin#180]
with the fuzzy reordering in https://github.com/ellie/atuin/pull/179, it is quite common to end up with a pile of identical commands sorted together. might it make sense to collapse these and only keep the most recent?

**Comment by ellie** [comment]
Totally would, duplicate commands are pretty redundant and would only really frustrate the user. Collapsing makes sense!

**Comment by mwotton** [comment]
blah. i'm sorry, i've just tested it now and this already works. not entirely sure why i thought it didn't.

While looking at it, though, I noticed the mechanism used to remove duplicates is quite slow, so I replaced it and benchmarked it - is significantly faster in my admittedly ad-hoc test, so i'll put in a PR.
