### ISSUE TITLE
fuzzy input support

### ISSUE THREAD

**Issue by crazycode** [ellie/atuin#186]
great command line tools, thanks.
suggest: 
When searching for history, I would like to support fuzzy matching, for example: `gpu` matches `git pull`

**Comment by Dav1d23** [comment]
I believe this is taken into account with #142

**Comment by crazycode** [comment]
> I believe this is taken into account with #142

Great job! but I found it not release yet.

**Comment by ellie** [comment]
I do need to cut a new release, sorry about that. The last few months have been very busy for me + after all the COVID lockdowns I've been spending minimal time in front of a screen!

I've got a few more things to merge + some cleanup to do, will get it sorted soon. If you want the features sooner, feel free to run `main`

Closing this.

**Comment by crazycode** [comment]
It's ok, thank you very much.
