### ISSUE TITLE
Issues when system date is far in advance

### ISSUE THREAD

**Issue by rickpayne** [ellie/atuin#189]

**Comment by rickpayne** [comment]
I had an issue on my laptop with suspend which caused the system date to be set a long way in advance. This then caused issues with atuin when it was trying to calculate the duration:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfRangeError(())', src/command/search.rs:45:67
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: atuin::command::search::draw
   4: atuin::command::search::select_history::{{closure}}
   5: atuin::command::AtuinCmd::run::{{closure}}
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: atuin::main`

I was able to fix this by deleting the offending entries from the history.db with

`delete from history where timestamp > 3111965300000000000;`

An example of a screwed up entry:
`603e6b2fe45742f5ae6c43f6dce2038f|3111965300517021519|38294589|0|date|/home/rickp|2440cee000ea453dadfa69a122d2db6e|clifford:rickp
`

**Comment by conradludgate** [comment]
Yeah seems that atuin assumes that all time entries happen in the past. It subtracts the provided timestamp from now and then tries to turn that into a human readable time like `5m ago` or `2wks ago`.

I suppose it's possible to check that time, see if it's in the future and change it to be `in 2wks`. Admittedly, that might be confusing but it would stop the panic

**Comment by ellie** [comment]
Yup this definitely needs sorting, thanks for raising it! An incorrect assumption for sure 

I've labelled this as a good issue to get started with. Happy to help anyone through it 👍

**Comment by TimB87** [comment]
Daylight saving time came in like a wrecking ball here
