### ISSUE TITLE
new user registration failed

### ISSUE THREAD

**Issue by kaosbeat** [ellie/atuin#190]
Tried the sync server, it fails for me

```
atuin register -u <I did insert a username here>  -e <i did insert my email here>  -p <not posting any passwords on git but it was here>
Error: failed to register user

Location:
    atuin-client/src/api_client.rs:56:20
```
when I try again I get
```
atuin register -u kaotec -e kasper.jordaens@gmail.com -p Mypassword
Error: username already in use

Location:
    atuin-client/src/api_client.rs:44:20

```
but when I try to sync

```

~$ atuin sync
Error: failed to get count (are you logged in?)

Location:
    /home/runner/work/atuin/atuin/atuin-client/src/api_client.rs:103:24

```

If I try to login supplying the key I got from `atuin key` I get `Error: invalid login details`

could it have been "special characters" in the password?

**Comment by ellie** [comment]
I've edited your password out of your comment, but I think because it ends with a ! and you didn't wrap it with ''

**Comment by conradludgate** [comment]
> I've edited your password out of your comment

Editing comments on github preserves history :grimacing:

**Comment by conradludgate** [comment]
On this. I think it might be wise to read the password from stdin rather than from args. Someone suggested it before and it would solve this kind of problem

**Comment by kaosbeat** [comment]
so the problem probably was my password contained a "!" and now I cannot register a new name with the same email address I guess?

**Comment by ellie** [comment]
> so the problem probably was my password contained a "!" and now I cannot register a new name with the same email address I guess?

Well, it's more an issue with how shells work, special characters have to be either properly escaped or in quotes 

I'm on holiday at the moment but I can sort the account when I'm home

Alternatively:

1) put a plus in the email "foo+bar@baz.com"
2) use another email
3) run your own server

**Comment by kaosbeat** [comment]
allright! 

1. was good enough as a workaround
Thanks

**Comment by tfriedel** [comment]
I had the same error when trying to use a custom server. The reason it failed was because the URL in the client config had a trailing '/' (i.e. http://myserver.com:8888/ ). After removing the trailing slash registering a user worked. I'm writing this in case someone else gets stuck with this error.

**Comment by conradludgate** [comment]
@tfriedel do you mind creating a new issue for this? I believe this is something we should be able to fix
