### ISSUE TITLE
Atuin throws errors when inside a deleted directory

### ISSUE THREAD

**Issue by ajeetdsouza** [ellie/atuin#195]
Steps to reproduce (on zsh):

```zsh
# Initialize Atuin.
eval "$(atuin init zsh)"

# Enter a deleted directory.
mkdir /tmp/x
cd /tmp/x
rm -rf /tmp/x

# Now, run any command.
echo
```

Atuin throws this error for every command run:

```
Error: No such file or directory (os error 2)

Location:
    /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1897:27
```

**Comment by conradludgate** [comment]
Interesting the panic isn't tracking the caller, I wonder what version of rust `atuin` was built with on your system. I'm going to try repro locally and maybe change some of the `unwrap`s to `expect`s

**Comment by conradludgate** [comment]
The error occurs within the `config` crate. The default behaviour allows relative paths, and `std::env::current_dir()` will error if the current directory does not exist.

https://github.com/ellie/atuin/blob/main/atuin-client/src/settings.rs#L137
https://github.com/mehcode/config-rs/blob/master/src/file/source/file.rs#L106

**Comment by conradludgate** [comment]
Since I don't think it makes sense for us to support relative paths for a config file, I think we could read in the file contents ourselves through our absolute path, and provide the string instead: https://docs.rs/config/0.11.0/config/struct.File.html#method.from_str

**Comment by conradludgate** [comment]
I also realise the panic is thrown outside of main, so I'm gonna make a separate PR that makes better use of eyre contexts. That should help these bug reports be more insightful

**Comment by ajeetdsouza** [comment]
Sounds awesome, thanks!
