### ISSUE TITLE
Unable to cross compile for Raspberry Pi Zero

### ISSUE THREAD

**Issue by aaronnewsome** [ellie/atuin#196]
Firstly, what an amazing project. I found it so useful, I run my own atuin server and I've installed the client on nearly all my machines.

It took a LOT of work to get this compiled to run on some machines. Some of my older machines like Ubuntu 14.04, I was just not able to get it compiled for. I currently have atuin running on about 90% of my systems, which is pretty impressive.

This issue is about Raspberry Pi Zero. I've successfully compiled atuin for aarch64 (rpi3 and rpi4). However, the rpi Zero binary 
 I've compiled doesn't seem to work. It compiles just fine, using cross ([https://github.com/rust-embedded/cross](https://github.com/rust-embedded/cross)). The binary seems to run on the rpi Zero. I was able to do **atuin import bash** and **atuin history list** without a problem on the rpi Zero.

I'm unable to login though. Here's the result from **atuin login** on the rpi Zero.

```
thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/blocking/shutdown.rs:51:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Has anyone been able to compile and run atuin on Raspberry Pi Zero?

**Comment by conradludgate** [comment]
Since the error suggests `tokio` (our asynchronous runtime), and the page for the RPi Zero says it's a single core device, I guess it's a threading issue. I think it might be reproducible on other environments if we configure tokio to be single threaded.

**Comment by conradludgate** [comment]
I looked into it, I think I should be able to get a fix out shortly
