### ISSUE TITLE
How should I pronounce the package name?

### ISSUE THREAD

**Issue by JUSTIVE** [ellie/atuin#204]
Hi, I'm one of the folks who really love the features what this project provides, and want to introduce this to my colleagues and friends.
But I'm having a major issue: how do I pronounce this project?

at first glance, I thought this should be supposed to pronounce as [A-tu-in] but after a few moments, it seems to be [æt-chu-in] or [æt-u-in].
I'm really confused right now, if any maintainer or anyone else out there who knows how to pronounce this name, please let me know so that I recommend this to my friends.

thanks! hope you have a good day

**Comment by conradludgate** [comment]
The former (ah-tu-in) is how I usually pronounce it. It comes from "The Great A'Tuin" from Terry Pratchett's Discworld series, so the A and Tuin parts are most likely distinct sounds

**Comment by JUSTIVE** [comment]
> The former (ah-tu-in) is how I usually pronounce it. It comes from "The Great A'Tuin" from Terry Pratchett's Discworld series, so the A and Tuin parts are most likely distinct sounds

Thanks for your kind reply with its origin. now I can recommend [Ah-tu-in] to my friends!

**Comment by ellie** [comment]
Haha, thank you for asking! Tbh I don't think there is an exact pronunciation, feel free to say it however you wish

There's also this, and a few other posts like it: https://www.reddit.com/r/discworld/comments/70qtjb/re_the_pronunciation_of_great_atuin/
