### ISSUE TITLE
create another release

### ISSUE THREAD

**Issue by SuperSandro2000** [ellie/atuin#212]
It would be nice to have another release to get https://github.com/ellie/atuin/commit/f55d5cf0bfa59af144788bec7c9d0a9ada71aad4 into distros.

**Comment by ellie** [comment]
For sure :) I'd originally wanted to get more into the next release but haven't had as much time as I'd hoped. Will try and sort something soon

**Comment by panekj** [comment]
Please include #202

**Comment by ellie** [comment]
Well I'm still not sure I want to merge that one, so we shall see.

**Comment by SuperSandro2000** [comment]
If not a lot changed maybe only bump the patch version? A 0.7.2 sounds reasonable to me. I am not in a hurry because I can quite easily fetch the patch into my stack via nix.

**Comment by ellie** [comment]
Done :)
