### ISSUE TITLE
Add key to switch search modes

### ISSUE THREAD

**Issue by ellie** [ellie/atuin#22]
Perhaps `ctrl-m` 

This could cycle between searching globally, per dir, or per session

**Comment by conradludgate** [comment]
Maybe use the search modes similar to https://lib.rs/crates/broot `/foo` is a regular expression. Ofc the slash is a valid command value, so maybe a `:` could work as the prefix

**Comment by ellie** [comment]
You're referring to this paragraph? 

> You may sort by launching broot with --sort-by-size or --sort-by-date. Or you may, inside broot, type a space, then sd, and enter and you toggled the :sort_by_date mode.

I like the idea of `:`! That would actually make it pretty similar to vim :thinking: 

so we could have:

`:sort-global`, `:sort-session`, `:sort-dir`- with `:sg`, `:ss`, `:sd` as short versions

Then as you suggest, `/foo`, `/^foo` etc would work as regex searches, while leaving off the `/` does the normal regex-less search

I really like this idea, thank you :D

**Comment by quentinmit** [comment]
Is this implemented now? I don't see any recent commits or PRs that address it.

**Comment by ellie** [comment]
Nope, I've closed it in favour of #118 

Just trying to tidy the issues up :)
