### ISSUE TITLE
`atuin sync` on new login not pulling complete history

### ISSUE THREAD

**Issue by conner** [ellie/atuin#226]
- Adding atuin to a new OS install
- Everywhere using `v0.7.1` except for new deployment
- New deployment with `v0.7.2` runs `atuin login --key .. --username .. --password ..`
- Pre-existing deployment has history of ~31k, new deployment ~14k

**Comment by conner** [comment]
Had a moment to take another shallow look at this:
- With a fresh `v0.7.1` install: `atuin login; atuin sync` takes a moment but gives me ~31k!
- Separately, returning to my box with `v0.7.2`: I try `atuin sync --force` and it gets me about there as well! (it actually has ~31k + 50 :upside_down_face: )

So what is `-f/--force` is intended to mean here and what criteria selected only a subset of history for that initial sync with the new version?

Meanwhile I now have that one command I couldn't quite remember that didn't arrive the first time, so :tada:

**Comment by TheOneValen** [comment]
I have a similar Problem with `0.8.0`. I deployed my own atuin server.

1st host ~38k entries
2nd host ~15k entries

Imported locally `atuin import zsh`. Imported fine (correct count (vs `wc -l`on both machines).

Registered on the first, login on the second. Ran sync -> I get ~70 entries on 1st that I ran on 2nd. My expectations would be that both machines now have ~43k entries.

**Comment by ellie** [comment]
Hey! So yes basically `atuin sync` tries to be smart and only sync what's needed, but... it's not particularly good at it atm. The force flag makes it fully sync everything and catch things that may have been missed

I'm working on a much better + more comprehensive sync at the moment which should catch all the edge cases that were missed in the first version :)

**Comment by ellie** [comment]
Since I've made a bunch of changes to the deployment + related code, I think this should be resolved. Happy to reopen if that is not the case!
