### ISSUE TITLE
Fix RISC-V build

### ISSUE THREAD

**Issue by Avimitin** [ellie/atuin#230]
The `atuin` package can't be built on the `RISC-V` environment. This is because the upstream crate `sodiumoxide` provides error build host information. There is a [patch](https://github.com/sodiumoxide/sodiumoxide/pull/474/commits/6dd994493ac592cf59798df75c293c6212c973a9) to fix this, but the `sodiumoxide` is deprecated and don't accept update anymore. So can you use this crate as a submodule and add this patch to build `atuin` in `RISC-V`.

**Comment by ellie** [comment]
Hey! I'd be happy to replace `sodiumoxide` with something that also supported RISC-V, but I'm not that happy with maintaining + patching a separate fork of our crypto library. Do you have any suggestions there?

**Comment by conradludgate** [comment]
I think our best solution would be moving away from sodiumoxide to something more supported. It will take a while to audit and verify other crates though

**Comment by Avimitin** [comment]
> Hey! I'd be happy to replace `sodiumoxide` with something that also supported RISC-V, but I'm not that happy with maintaining + patching a separate fork of our crypto library. Do you have any suggestions there?

I am sorry that I don't know much about Rust crypto crates.

**Comment by shinzui** [comment]
I think the `sodiumoxide` issue affects M1 machines running Monterey (#220), so replacing the deprecated crate would be good for the project.

**Comment by ellie** [comment]
Hey @shinzui 

I can confirm that Atuin both builds and runs totally fine on an M1 machine running Monterey - I type this to you now from one. 

There aren't any large and obvious replacements to `sodiumoxide` just yet, and seeing as it will still be getting security updates we won't be prioritizing replacing it just yet

**Comment by shinzui** [comment]
@ellie Got it. I replied on the other issue before seeing your reply here.

**Comment by panekj** [comment]
Perhaps https://github.com/RustCrypto/nacl-compat can be used?

**Comment by ellie** [comment]
I don't think that library would solve our problem either, as it doesn't seem to have been audited.

I'm going to close this for now as I don't see us changing it in the near future, and much as I'd love to support RISC-V, I don't want to do it at the expense of a secure cryptographic library

Should this change, I'd be happy to replace the library! Tbh it does also slow our compilation as well, so it's a win-win
