### ISSUE TITLE
Generate shell completions

### ISSUE THREAD

**Issue by orhun** [ellie/atuin#232]
Hey!

Is there a way to generate shell completions for `atuin`? I saw this line in the release workflow but I'm not sure if it is related:

https://github.com/ellie/atuin/blob/d3059af815130f102dd97cb1d1e5030920754105/.github/workflows/release.yaml#L119

(Also, the contents of this directory seems to be empty.)

If it doesn't exist yet, do you have any plans to work on this? e.g. using [clap::App::gen_completions](https://docs.rs/clap/2.34.0/clap/struct.App.html#method.gen_completions)

I'd be happy to submit a PR about this 🐻

**Comment by ellie** [comment]
I was totally planning on doing so! But would definitely welcome a PR if you're happy sorting that out for us ☺️ Using the clap completions generator makes sense
