### ISSUE TITLE
Default keybindings don't work in Fish

### ISSUE THREAD

**Issue by mrjones2014** [ellie/atuin#240]
Hi, sorry if I'm just doing something wrong. I built and installed from source by cloning the repo and running `cargo install --path .`, then added `atuin init fish | source` to my `config.fish` like the README.md says to. However, neither `ctrl+r` or up arrow seem to trigger atuin.

The keybinding docs also don't have a section for Fish.

**Comment by mrjones2014** [comment]
it seems like the keybindings started working after manually running `_atuin_search`?

**Comment by mrjones2014** [comment]
Hm, it seemed to work once or twice. Now not working again. Weird.

**Comment by mrjones2014** [comment]
I'm also using tmux, if that may be relevant.

**Comment by mrjones2014** [comment]
Hmm, even if I manually run `bind -k up '_atuin_search'` it doesn't work so I'm not 100% sure it's actually an issue with this, but rather, it's probably an issue with my fish or tmux config.

**Comment by mrjones2014** [comment]
ah, when using fish vi bindings, it works in normal mode but not insert mode

**Comment by mrjones2014** [comment]
If you're interested, it seems to be a bug in fish shell with `fish_vi_key_bindings`

https://github.com/fish-shell/fish-shell/issues/8554

**Comment by conradludgate** [comment]
Curious. Thanks for testing and investigating! We should definitely add a note for this. Docs could use a little bit of love anyway

**Comment by mrjones2014** [comment]
No problem! Just discovered this project this morning, and I can already see this completely transforming my workflow! Really amazing project, thank you!

**Comment by mrjones2014** [comment]
@conradludgate @Ellie looks like this will be fixed in fish shell 3.4. Can we also check from this tool whether `fish_vi_key_bindings` is enabled, and if so, also bind `k` (in vi mode, you use h/j/k/l as arrow keys) in normal mode?

If you're open to this change, I can work on getting a PR up to implement this.

**Comment by conradludgate** [comment]
I dont think a PR is necessary. You can bind more keys yourself in your own fish config file. I think manually supporting some shell extensions might be a lot of work in the long run
