### ISSUE TITLE
After importing my `fish_history` I get an error about argument list being too long

### ISSUE THREAD

**Issue by mrjones2014** [ellie/atuin#241]
After running `atuin import fish`, when I start a new shell, `atuin init fish | source` now gives the following error:

```
Failed to execute process '/opt/homebrew/bin/starship'. Reason:
The total size of the argument and environment lists 1.5MB exceeds the operating system limit of 1MB.
Try running the command again with fewer arguments.
Failed to execute process '/opt/homebrew/bin/starship'. Reason:
The total size of the argument and environment lists 1.5MB exceeds the operating system limit of 1MB.
Try running the command again with fewer arguments.
```

**Comment by mrjones2014** [comment]
Is there a way to _unimport_ my history or drop some rows in the mean time?

**Comment by conradludgate** [comment]
Huh. Not sure why starship would be interacting that way with atuin

**Comment by mrjones2014** [comment]
I think because Starship checks the exit code of the last command and makes the prompt red if it's non-zero. I don't think that's relevant.

Is the `ATUIN_HISTORY` environment variable defined like so used for anything?

```
set -gx ATUIN_HISTORY (atuin history list)
```

removing that line from `src/shell/atuin.fish` fixes it, and it seems like everything still works properly.
