### ISSUE TITLE
Scrolling should have an offset that keeps the 1-9 labels in view

### ISSUE THREAD

**Issue by mrjones2014** [ellie/atuin#244]
Gif to demonstrate what I mean:

![CleanShot-2021-12-17-at-08 30 44](https://user-images.githubusercontent.com/8648891/146552086-4e07c63a-b05b-4314-b236-d3c276df680f.gif)

It should start scrolling when the `9` in the leftmost column reaches the top line instead of the numbers scrolling off screen.

**Comment by mrjones2014** [comment]
Looks like its not currently possible to fix this but will be at some point in the future.

https://github.com/fdehau/tui-rs/issues/328

**Comment by conradludgate** [comment]
Should probably be fixed but it's definitely a niche issue, so I wouldn't put priority on this

**Comment by ellie** [comment]
Resolved by #524!
