### ISSUE TITLE
Allow recording of and filtering by current shell identifier (e.g. PID or PID + uptime)

### ISSUE THREAD

**Issue by s0** [ellie/atuin#253]
This may be a somewhat unique use-case, but figured I'd open an issue in case anyone else feels the same.

I often find myself either:

* Arranging my terminals / shells for common jobs / workflows (e.g. running tests in my left shell and i/o / git ops in my right shell)
* Running a series of commands repeatedly (e.g. when doing an interactive rebase)

For both these circumstances, having the shell history act in a global manner rather than just the current session + previous history (as is default for most shells) causes more fraustration than benefit.

I could solve this problem by just unbinding atuin from `up`, and using `^R` when i want a full search, relying on my shell's default history navigation... but I like atuin, and don't want to reduce my usage of it because of a few use cases...

Perhaps we could do something like this to remain backwards-compatible with the current behaviour?

* Update the schema to allow for shell identifier to be stored (probably allow for an arbitrary string in case the user want's to use some other type of identifier for their shells than just a PID, perhaps combining it with their `uptime --since`, to make it more unique)
* Allow for a shell identifier to be given as an argument to `atuin history`
* Allow for a shell identifier to be specified in `atuin search`
* Then either:
  * A:
    * Restrict the search to commands with the given identifier
    * Introduce a keybinding for interactive search that allow you to toggle "global" mode when an identifier was given
  * B:
    * Order the results so that results for the current shell are shown at the bottom, and everything else above that.

**Comment by ellie** [comment]
Resolved with #329 :D
