### ISSUE TITLE
Unused Dependencies

### ISSUE THREAD

**Issue by Laura7089** [ellie/atuin#254]
The project has a large dependency tree which lengthens compile times a little - a quick bit of tinkering seems to reveal several dependencies and features which `atuin` never uses:

- `fork` is never invoked
- `cli-table`'s default features are never used
- `warp`'s default features are never used

**Comment by lmburns** [comment]
None of these are used

`atuin`
- `fork`

`atuin-client`
- `fern`
- `humantime`
- `indicatif`

`atuin-common`
- `eyre`
- `rmp-serde`

`atuin-sever`
- `chrono-english`
- `directories`
- `fern`
- `fork`
- `indicatif`
- `parse_duration`
- `rmp-serde`
- `unicode-width`
- `urlencoding`

**Comment by Sciencentistguy** [comment]
`cargo-udeps` seems to suggest that there are no longer any unused deps, so this issue could be closed.
