### ISSUE TITLE
Error on first sync: failed to get count (are you logged in?)

### ISSUE THREAD

**Issue by Elvander** [ellie/atuin#255]
Hi,

After doing the first sync, I get the following error.

```
 ~ atuin sync
Error: failed to get count (are you logged in?)

Location:
    /home/xyz/.cargo/registry/src/github.com-1ecc6299db9ec823/atuin-client-0.8.0/src/api_client.rs:105:24

```
But I'm logged in. To be sure I've logged out and back in ...

**Comment by Mellbourn** [comment]
Same problem. 
Logging out and in again does not help, even though logging in reports being successful: "Logged in!"
Rebooting does not help.
Pinging api.atuin.sh works
Surfing to https://api.atuin.sh/ works.

This is running on macOS Monterey 12.1 on an M1 MacBook.
Installed using homebrew. Version 0.8.0

**Comment by Syzygianinfern0** [comment]
Did you manage to fix it? I am facing the exact same issue!

**Comment by Syzygianinfern0** [comment]
Maybe ping @conradludgate

**Comment by ellie** [comment]
It looks like the CPU on my database server is at 100% 😂 

I'll look at getting this scaled up soon, hopefully I can find a less expensive way of doing that. In the meantime I'd suggest hosting your own server :)

**Comment by Syzygianinfern0** [comment]
> It looks like the CPU on my database server is at 100% joy
> 
> I'll look at getting this scaled up soon, hopefully I can find a less expensive way of doing that. In the meantime I'd suggest hosting your own server :)

Haha! Thank you very much for your reply :smile:

**Comment by ellie** [comment]
I've scaled this up now, and CPU usage seems much better! It's costing me quite a bit more now though 😓 

Please let me know if there's any other issues!
