### ISSUE TITLE
Build ARM docker image

### ISSUE THREAD

**Issue by Mellbourn** [ellie/atuin#269]
When I try to run the atuin docker image on my MacBook it fails:

```
> docker run -d -v "atuin:/config" ghcr.io/ellie/atuin:latest server start
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

This is a MacBook Pro 2021 with the Pro M1 processor running macOS Monterey 12.1

**Comment by conradludgate** [comment]
That warning is not an explicit failure. That's just saying that docker is enabling x86 emulation in order to run the image.

That being said, having an arm image might good for us to provide
