### ISSUE TITLE
atuin server randomly crashes when running for a while

### ISSUE THREAD

**Issue by SuperSandro2000** [ellie/atuin#272]
My ``atuin server`` frequently crashes with the following error:

```
ERROR atuin_server::handlers::history > failed to add history: error returned from database: value too long for type character varying(8192)
```

I think I have multiple entries in my history which have a base64 compressed length of 7500 characters. This is probably to much combined with the encrpyted data. Is there an easy way I could delete such entries from my history? Or should I patch atuin to increase the size of this field?

**Comment by ellie** [comment]
I'd be happy to increase the max size of this field, as I doubt you'll be the only one running into this problem! Perhaps 16,384?

We'd need to create another database migration, but beyond that there shouldn't be much else required

**Comment by SuperSandro2000** [comment]
The history entries that are causing trouble are base64 strings which I decoded. I think in addition to that we should strip or ignore to long commands to prevent further issues like this.

**Comment by ellie** [comment]
Need some thinking around proper validation here, we can't just ignore insertions because then remote/local have different history + won't sync very well

For now I've partly mitigated this in #321, and will see how this goes

**Comment by jirutka** [comment]
First of all, the server should never crash on invalid/malformed/whatever input, that’s DoS vulnerability.

**Comment by ellie** [comment]
> First of all, the server should never crash on invalid/malformed/whatever input, that’s DoS vulnerability.

The server doesn't actually crash on a long entry, but the handler does error out.

@SuperSandro2000 I've just merged #447 which should help you out - you can try increasing `max_history_length` to some larger value that suits your needs, or set it to 0 if you trust everyone with an account on your server (then history length is unrestricted)

**Comment by SuperSandro2000** [comment]
I am already happy if the handler is no longer crashing.

**Comment by ellie** [comment]
It doesn’t crash, just logs an error that the input is invalid :)
