### ISSUE TITLE
Missing the ISSUE TEMPLATES and the Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [ellie/atuin#274]
The project is currently missing the **ISSUE TEMPLATES** and the **Code of Conduct**.  With the issue templates, you can encourage contributors to include specific, structured information by using issue forms in your repository, and the code of conduct defines standards for how to engage in a community. If you want to add those, then I would be happy to add a PR.

**Comment by ellie** [comment]
I get the purpose of the issue template, but I'm not 100% sure we need it for now

Otherwise I've added a code of conduct! Thanks for your interest in the project :)
