### ISSUE TITLE
How do I use a custom server?

### ISSUE THREAD

**Issue by Syzygianinfern0** [ellie/atuin#277]
I have a docker instance running successfully. 

```
CONTAINER ID   IMAGE                      COMMAND                  CREATED         STATUS         PORTS     NAMES
ba6c70cc0f12   ghcr.io/ellie/atuin:main   "/usr/local/bin/atui…"   7 seconds ago   Up 6 seconds             vigorous_leavitt
```

How do I configure atuin to use this for registrations and logins? Do I have to edit the [sync address](https://github.com/ellie/atuin/blob/main/docs/config.md#sync_address) in some way?

**Comment by Syzygianinfern0** [comment]
@ellie @conradludgate what do I set the sync address as? I have tried the `host:port` as I have set it in my `server.toml`, but I get something like this: 

```
Error: error sending request for url (http://127.0.0.1:8888/sync/count): connection error: Connection reset by peer (os error 104)

Caused by:
   0: connection error: Connection reset by peer (os error 104)
   1: Connection reset by peer (os error 104)

Location:
    /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1914:27
```

How do I use my custom server?

**Comment by Syzygianinfern0** [comment]
This is how I start my server

```shell
docker run -v "$HOME/.config/atuin:/config" ghcr.io/ellie/atuin:main server start
```

I'm sure that my database is connected properly as I see a few empty tables created called users, history, session, etc.

**Comment by conradludgate** [comment]
When running in docker, make sure that the host address is set to `0.0.0.0`. Then when you run the image, you'll need to expose the correct port, eg
```sh
docker run -v "$HOME/.config/atuin:/config" -p 8888:8888 ghcr.io/ellie/atuin:main server start
```

**Comment by Syzygianinfern0** [comment]
Wow! Thanks for your response! It works now 🎉🎉🎉

Can I send in a PR explicitly mentioning the port exposing and setting the client side config for the sync address in the [docs](https://github.com/ellie/atuin/blob/main/docs/server.md)?

**Comment by ellie** [comment]
@Syzygianinfern0 Glad you got it sorted! And yes, a PR would be greatly appreciated 😊
