### ISSUE TITLE
Switch to Crossterm TUI backend

### ISSUE THREAD

**Issue by ellie** [ellie/atuin#283]
tui has switched to crossterm as the default, instead of termion

The reasoning given is here: https://github.com/fdehau/tui-rs/pull/553

I think it's pretty reasonable, and would probably make sense for us to switch too. Especially for the extra platform support :)

**Comment by conradludgate** [comment]
I made a start in the ``crossterm` branch, but it's currently not working 100%

- Fails to launch on 'up' keybinding
- Fails to respect up/down keys in the TUI (ctrl-n/p work fine)

**Comment by ellie** [comment]
Hmmm I see, I wonder if it is listening to different escape codes or something. Perhaps it needs enabling 🤔
