### ISSUE TITLE
Keybinds don't work by default in Fish shell if using `fish_vi_keybindings`

### ISSUE THREAD

**Issue by mrjones2014** [ellie/atuin#290]
For the key binds to work in insert mode when using `fish_vi_keybindings` you have to pass `-M insert` for insert mode (`bind` defaults to `default` mode which is what Fish calls vi normal mode).

So the following block:

```
bind -k up _atuin_search
bind \eOA _atuin_search
bind \e\[A _atuin_search
```

should be:

```
bind -k up _atuin_search
bind \eOA _atuin_search
bind \e\[A _atuin_search
bind -M insert -k up _atuin_search
bind -M insert \eOA _atuin_search
bind -M insert \e\[A _atuin_search
```

I'm happy to work on a PR for this, after I'm finished work today.

**Comment by mrjones2014** [comment]
Oh, actually looks like it's already there. I guess it just isn't released yet?

**Comment by ellie** [comment]
Yup that's right! @patricksjackson did it in #265!

Thanks for opening this though, I appreciate the consideration! I'm working on releasing the work since v0.8.0 at the moment so it should be out today and working itself into package managers over the next few days :)

**Comment by ellie** [comment]
Closed as a dupe
