### ISSUE TITLE
Problems Keybinding

### ISSUE THREAD

**Issue by drag0n141** [ellie/atuin#330]
Hi, i have problem when set export ATUIN_NOBIND="true". Enter on an entry or alt + num does not work.

**Comment by jungshik-jang** [comment]
Same here. any update?

**Comment by conradludgate** [comment]
Hey, this is a very hard problem to debug without more information unfortunately. If you're using `ATUIN_NOBIND=true`, how are you running invoking the atuin search, maybe that can help us debug. Thanks

**Comment by drag0n141** [comment]
Hi, i am open autin over the command "atuin search -i" and using the terminal fish

**Comment by drag0n141** [comment]
I am open it now with "_atuin_search" this does work.
