### ISSUE TITLE
Some runtime issues with atuin 0.9.1

### ISSUE THREAD

**Issue by chenrui333** [ellie/atuin#339]
Tried to upgrade atuin formula, but found some runtime issues. 

```
atuin history list
thread 'main' panicked at 'failed to find ATUIN_SESSION - check your shell setup: NotPresent', /Users/rui/.cargo/registry/src/github.com-1ecc6299db9ec823/atuin-client-0.9.1/src/database.rs:30:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

build log, https://github.com/Homebrew/homebrew-core/runs/6144595989
relates to Homebrew/homebrew-core#99995

**Comment by conradludgate** [comment]
Hi, thanks for reporting.

Which shell are you running? Can you try start a new shell/source your rc file? And can you confirm that you have `atuin init ...` in that file too

**Comment by conradludgate** [comment]
Oh, I see now that it's failing in CI. Will look into it more now that I'm home

**Comment by conradludgate** [comment]
Ok, I've left a comment on the formula PR. This is expected. The formula doesn't actually run the init script, meaning atuin is never initialised. This obviously means that atuin is non functional (we just haven't used that session variable in that specific codepath before)

**Comment by ellie** [comment]
I've commented on the Homebrew issues, but pasting it here for clarity

> Using ATUIN_SESSION=literallyanyvalueatall atuin history list instead should work - we do expect this variable to be present

**Comment by ellie** [comment]
We _could_ make atuin more resilient to a not-set ATUIN_SESSION variable, but in all real-world usage not having this variable set is indicative of a broken install

**Comment by chenrui333** [comment]
Got you, let me give that a try.

**Comment by chenrui333** [comment]
Setting `ATUIN_SESSION` worked for me, thanks!

**Comment by conradludgate** [comment]
> Setting `ATUIN_SESSION` worked for me, thanks!

And thank you for maintaining the formula. Much appreciated

**Comment by chenrui333** [comment]
np :)
