### ISSUE TITLE
UI: increase of keystrokes to increase previous command - feature request

### ISSUE THREAD

**Issue by drahnr** [ellie/atuin#358]
I tried atuin, and I it's helpful when investigating a command that's further back. For the immediate use case of re-running the previous command, it requires an additional keystroke and flashes the entire terminal twice which is a rather large visual overhead.

# Feature request:

Allow to configure a number of ups before opening the full TUI.

**Comment by redsfyre** [comment]
Actually, there is a configuration for this. It's not exactly what you want, but you can make it work with just the ctrl+R shortcut instead of both ctrl+R and arrow keys. Or vice versa. For detailed information https://github.com/ellie/atuin/blob/main/docs/key-binding.md#key-binding

**Comment by jirutka** [comment]
> …flashes the entire terminal twice which is a rather large visual overhead.

This exactly. I think that atuin shouldn’t bind the Up Arrow key by default, its UI is really not good fit for this.

**Comment by conradludgate** [comment]
> Allow to configure a number of ups before opening the full TUI.

I'm not sure if it's even possible to register different up-key handling like this. My only suggestion would be to disable the default keybinding and create your own.

If someone better at shell than I knows of a way we can do this across all our currently supported shells, then I'd be happy to assist in getting that feature planned out

> its UI is really not good fit for this

It's certainly not what you're used to. I found it intrusive in the beginning but now I struggle to use a terminal without it. So I would try to avoid stating personal opinions like this as fact

**Comment by ellie** [comment]
I'm going to be closing this one for now - it is very unlikely we will ever implement this, and if your workflow requires it then you can implement it in your own shell config

> For the immediate use case of re-running the previous command, it requires an additional keystroke and flashes the entire terminal twice which is a rather large visual overhead.

If this is something that bothers you, then I'd suggest setting ATUIN_NOBIND and perhaps just binding to ctrl-R. I know some people prefer Atuin launching immediately on the up arrow, and some don't, so really it just comes down to configuring your shell to your preference.

Alternatively, you might prefer the compact UI mode.
