### ISSUE TITLE
Translation plan

### ISSUE THREAD

**Issue by OnePieceJoker** [ellie/atuin#360]
As the title says, I think it's possible to add some documentation in other languages to atuin. 

In the next few days, I will be submitting a PR for the Chinese language translation. 

If you also have translation plans, you can communicate here

**Comment by mb6ockatf** [comment]
Can translate anything to russian if anyone want it
@OnePieceJoker which files are for translation? I may be blind but I cannot find 😶

**Comment by ellie** [comment]
> Can translate anything to russian if anyone want it

Yes please @mb6ockatf! That would be fantastic <3
