### ISSUE TITLE
support multi device and fzf search

### ISSUE THREAD

**Issue by Eloco** [ellie/atuin#362]
i register a account in one device, and i print the key,
after import and sync
i login to other device, try to sync and merge all the history,

but it got some issue:
some device sync success but cant merge,
some device got a error (with same key): 
```
thread 'main' panicked at 'failed to decrypt history! check your key: failed to open secretbox - invalid key?

Location:
    /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/atuin-client-0.9.1/src/encryption.rs:99:22', /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/atuin-client-0.9.1/src/api_client.rs:139:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

and due to atuin use ctrl+r, which same with fzf,
please support fzf search will let it search more smart

**Comment by ellie** [comment]
Hmm. Would you be able to try again please? The server has been having some issues today after _even more_ load, and I just deployed a change. Will also be scaling up later today

Also please _double_ check that 

1) You are logged in as the same user on both machines. Checking your session file can help there, `~/.local/share/atuin/session`
2) Your keyfiles match exactly, use `atuin key`

**Comment by ellie** [comment]
Also, in terms of `fzf` - our fuzzy mode was modeled after the search there, although ofc it's not exactly the same algorithm.

There's an issue here you may find useful: https://github.com/ellie/atuin/issues/68

**Comment by jack-fireworkhq** [comment]
![maim-full-20220504-102642](https://user-images.githubusercontent.com/80802145/166608060-7aa9dcfd-e0c1-4cad-bccc-4c54177d97c8.png)
Hi @ellie , I have met the same problem today. I register on my PC and everything works great on it, then I login on my laptop I met this.
My os is "5.10.105-1-MANJARO", and I tried with both zsh and bash but all failed.
Thank you for greating such a great project BTW😀

**Comment by JackTheMico** [comment]
![maim-full-20220504-102642](https://user-images.githubusercontent.com/19216598/166608840-7d59209a-373b-4d17-9e99-2d9e11a099f9.png)
Hi @ellie , I have met the same today. I registered on my PC and it works fine, but when I login on my laptop I met this. I tried it with both zsh and bash, my OS is "5.10.105-1-MANJARO".
Thank you for creating such a great project BTW😀

**Comment by ellie** [comment]
Hey @jackthemico

I've deleted your comment as the screenshot revealed some of your details

**Comment by Eloco** [comment]
Hi @ellie 

latest i try again atuin, it runs good.
tks for the nice tools .

BTW i make it fit fzf by comment the line  ` bindkey '^r' _atuin_search_widget`  from `atuin init zsh` and source it.
```
myzsh=`readlink -f ${HOME}/.zshrc`
mydir=`dirname ${myzsh}`
source ${mydir}/atuin.zsh
```
