### ISSUE TITLE
macOS bash press Enter return nothing in Ctrl-R search window

### ISSUE THREAD

**Issue by jiacai2050** [ellie/atuin#371]

**Comment by ellie** [comment]
Sorry, but without more detail it's unlikely we will be able to help you. Please provide more detail when submitting an issue - eg

- what you did
- what you expected to happen
- what actually happened

**Comment by conradludgate** [comment]
We've seen another incident of this issue. Upon diagnosis, the conclusion is that the default MacOS bash install is an old version 3. We don't officially support this and we suggest upgrading to at least bash 5 which can be done using brew.
