### ISSUE TITLE
Analysing data on a self hosted atuin server

### ISSUE THREAD

**Issue by satyarths** [ellie/atuin#385]
I'm running atuin with a local network Postgres instance to self host my data.
 I was hoping to run queries on that data but realized from https://github.com/ellie/atuin/blob/main/atuin-client/src/encryption.rs that all the data was encrypted by default 😄 . Which is a great design default. 

Was wondering if you'd have any recommendations on how could I run some more complex queries beyond what  `stats` currently offers.

**Comment by conradludgate** [comment]
All the data from the sync server should be mirrored with your client database. So you should be able to do the types of analysis on your local sqlite file (should be found in `.local/share/atuin` by default)

**Comment by satyarths** [comment]
Thanks will look into that. 
 But not incase I use the server for multiple clients though?

**Comment by satyarths** [comment]
Ah okay thanks! that works for me.

**Comment by satyarths** [comment]
Apologies on reopening this, but I'm using a mac and I cannot find the db at `~/Library/Application Support/com.elliehuxtable.atuin/history.db` .  or the path you pasted above.  Any suggestions on where this file maybe located?

**Comment by satyarths** [comment]
nvm, found it `/System/Volumes/Data/Users/<username>/.local/share/atuin`

**Comment by satyarths** [comment]
@conradludgate  can you help confirm if this is expected? If so should the default config file and readme be updated to reflect this.

**Comment by conradludgate** [comment]
In docs/config.md

> We store data in `~/.local/share/atuin` (unless overridden by XDG_*).
