### ISSUE TITLE
long command lines

### ISSUE THREAD

**Issue by khuongduybui** [ellie/atuin#405]
hi Ellie, first of all thanks a lot for the awesome tool!
I'm having problems browsing my history (with up key) when the command lines are longer than the terminal width, I can't see the end of it. This is particularly problematic when I'm playing with `jq` because my command often starts with
`cat ... | grep ... | sed ... | xargs ... | <a bunch of other things> | jq ` so by the time I get to my jq query, the command is already longer than terminal width and if I hit "up" to see what I had before, I couldn't possibly know which one is which.

**Comment by ellie** [comment]
> hi Ellie, first of all thanks a lot for the awesome tool!

thank you for the kind words! 😁 

Hmm. A potential solution here would be for us to break it between multiple lines, basically just wrap when we hit the edge of the terminal

**Comment by iamkroot** [comment]
I would suggest a different approach to this- add a Preview window to the right. It would show not just the command, but also other details such as Host, Directory, etc.

This is the main thing I miss after migrating from https://github.com/m42e/zsh-histdb-fzf (includes an asciinema sample).

**Comment by conradludgate** [comment]
We have preview window support for now, below the terminal line.

> add a Preview window to the right. It would show not just the command, but also other details such as Host, Directory, etc.

We have a vision to add this. But we're tracking this elsewhere so I'm closing this issue
