### ISSUE TITLE
How to properly delete an entry?

### ISSUE THREAD

**Issue by iaeiou** [ellie/atuin#413]
Hi there,

I'm trying to clean up some lines from Atuin history but failed so far.

Here is what I tried:

- I installed `sqlitebrowser`
- I opened the database from `~/.local/share/atuin/history.db`
- From the tab `Browse Data`, I've selected the table `history`
- Some lines was successfully deleted, and the database saved

Unfortunately, these lines still appear when I hit `Ctrl+R`.

I suspected some cache or backup files, so I moved `history.db-shm` and `history.db-wal` and tried again.
I also checked from a fresh terminal window.

These damned lines are still here..

Note that I didn't configure any synchronization.

What am I missing?

**Comment by ellie** [comment]
could you try deleting them via the `sqlite3` CLI?

ie

```
delete from history where command = 'the command you want to delete';
```

**Comment by iaeiou** [comment]
It works, but only partially:

the command still appears on the first screen, right after hitting `Ctrl+R`.

It does not appear anymore when the results are filtered (after hitting any keystroke, even if the filter corresponds to the string that appeared previously)

I ran the command you gave me and also checked the content of `.bash_history`.

**Comment by ellie** [comment]
does it show up if you run

```
select * from history where command = 'the command you want to delete';
```

because otherwise I really can't see a way that it would still exist 🤔

**Comment by iaeiou** [comment]
It does not appear in `sqlite` when I run

    select * from history where command = 'the command you want to delete';

**But still** appears on the first screen of `atuin` when I hit `Ctrl+R`.. weird..

**Comment by ellie** [comment]
Unfortunately I can't replicate the issue :(

Can you try running `VACUUM` after you delete?

another thing to try. does `strings ~/.local/share/atuin/history.db` contain your command, after you delete it + vaccuum?

**Comment by ellie** [comment]
Closing as stale

**Comment by ebardie** [comment]
Enter the new Inspector mode by pressing <ctrl>-o on the command you wish to zap, and then press <ctrl-d> to delete.

Whilst this is a two step process, it's less of a faff than messing with the sqlite db file, or working out a tight search pattern.

I'm running Atuin v18.2.0, and CBA to look up when Inspector mode landed; you may need to upgrade.

**Comment by ellie** [comment]
Absolutely do the above.

Please don't manually delete from sqlite, as it'll just come back when you run a sync
