### ISSUE TITLE
Keeping typed query on exit when Esc is pressed

### ISSUE THREAD

**Issue by pdecat** [ellie/atuin#422]
Similar to what fzf provides with `--bind esc:print-query` in `FZF_CTRL_R_OPTS` (see 
https://github.com/junegunn/fzf/issues/1922#issuecomment-734017396), it would be nice to be able to keep the typed query when exiting atuin with the Escape key.

**Comment by conradludgate** [comment]
I think this is reasonable, although it should be configurable IMO

**Comment by ellie** [comment]
I'd be happy to get this one out, but I think it would also make a pretty good first issue for someone. Happy to help out + provide guidance if required!

**Comment by pdecat** [comment]
Working perfectly, thanks!
