### ISSUE TITLE
Use already typed command line as base query when pressing Ctrl-R

### ISSUE THREAD

**Issue by pdecat** [ellie/atuin#428]
It would be awesome to use what the user has already typed on the command line as the base query when pressing Ctrl-R to launch the search UI.

**Comment by conradludgate** [comment]
I'm not sure how your shell is set up, but this has worked since day1 for me. Can you share what shell you use and how you init atuin?

**Comment by norpol** [comment]
I've just tested it too, so seems in Bash 4 and 5 it doesn't work but on zsh it does.

**Comment by dotsam** [comment]
I noticed this a while back too but never got around to confirming I had the right fix and opening a PR.

I ended up replacing `$BUFFER` here with `$READLINE_LINE`
https://github.com/ellie/atuin/blob/dcdde22511fe4e663476a92695208cdd130a7caa/src/shell/atuin.bash#L21

**Comment by dotsam** [comment]
(This should maybe be a separate issue, but bash also doesn't get the `up` rebind mentioned in the README and that zsh and fish seem to have)
