### ISSUE TITLE
Missing history entries and importing multiple times

### ISSUE THREAD

**Issue by lnicola** [ellie/atuin#446]
Hi! I just installed `atuin` (on a single PC) and didn't get a chance to play much with it, but I'm confused about its handling of the history. More specifically:

```bash
# two days ago
$ atuin import auto
$ atuin sync

# today I noticed a missing entry in `Ctrl-R`
$ atuin sync
Sync complete! 10348 items in database, force: false
$ wc -l .zhistory
10273 .zhistory
$ atuin import zsh
        Atuin         
======================
          🌍          
       🐘🐘🐘🐘       
          🐢          
======================
Importing history...
Importing history from bash # umm, okay?
$ atuin import auto
        Atuin         
======================
          🌍          
       🐘🐘🐘🐘       
          🐢          
======================
Importing history...
Detected ZSH
Importing history from bash
$ atuin sync
Sync complete! 30457 items in database, force: false

# oh no, I suppose I duplicated my history

# still not working
$ rg unbound .zhistory
4763:ps aux | rg unbound
5061:diff -u /etc/unbound/unbound.conf /etc/unbound/unbound.conf.pacnew
5253:man unbound
5254:man unbound.conf
6154:sudo -e /etc/unbound/unbound.conf
9347:cat /etc/unbound/unbound.conf
9644:sudo systemctl restart unbound
10274:: 1654839965:0;rn unbound ~/.zhistory
10279:: 1654840132:0;atuin search unbound
10281:: 1654840393:0;rg unbound .zhistory
$ atuin search unbound
```

So it appears that:

 - importing the history worked, but some entries are missing
 - running `atuin import` duplicates the entries

Sorry if this is documented, but I didn't see anything about it.

EDIT:

```
$ sqlite3 ~/.local/share/atuin/history.db "select command from history where command like '%unbound%'"
atuin search unbound
atuin search unbound
cat /etc/unbound/unbound.conf
cat /etc/unbound/unbound.conf
cat /etc/unbound/unbound.conf
diff -u /etc/unbound/unbound.conf /etc/unbound/unbound.conf.pacnew
diff -u /etc/unbound/unbound.conf /etc/unbound/unbound.conf.pacnew
diff -u /etc/unbound/unbound.conf /etc/unbound/unbound.conf.pacnew
man unbound
man unbound
man unbound
man unbound.conf
man unbound.conf
man unbound.conf
ps aux | rg unbound
ps aux | rg unbound
ps aux | rg unbound
rg unbound .zhistory
rn unbound ~/.zhistory
rn unbound ~/.zhistory
sqlite3 ~/.local/share/atuin/history.db "select command from history where command like '%unbound%'"
sqlite3 ~/.local/share/atuin/history.db 'select command from history where command like '%unbound%';'
sudo -e /etc/unbound/unbound.conf
sudo -e /etc/unbound/unbound.conf
sudo -e /etc/unbound/unbound.conf
sudo systemctl restart unbound
sudo systemctl restart unbound
sudo systemctl restart unbound
```

 - the entries get duplicated because they don't have timestamps in my `.zhistory`, and they get added with the import time
 - the entries were imported correctly, but for some reason they don't show up in search

**Comment by lnicola** [comment]
Ah, this is because search only looks at the command and not the arguments?

**Comment by conradludgate** [comment]
> running atuin import duplicates the entries

Yeah that seems likely. Without complicating our import further, it seems like something I'd rather not fix.

> Importing history from bash # umm, okay?

Looks like I bugged the import in my last round of updates

**Comment by conradludgate** [comment]
To undup your history, you'll likely have to register a new account for now :/ deletion of synced history is still a WIP

**Comment by lnicola** [comment]
> Yeah that seems likely. Without complicating our import further, it seems like something I'd rather not fix.

I'd have expected `import` to be more or less idempotent.  Do you know what the timestamps are used for?

> To undup your history, you'll likely have to register a new account for now :/ deletion of synced history is still a WIP

At least they seem to be deduped in the UI.

**Comment by conradludgate** [comment]
> I'd have expected import to be more or less idempotent. Do you know what the timestamps are used for?

Not all history formats have timestamps, it would be good if we had some special cases for these, but I don't expect that people should be importing multiple times.

Our current logic literally just parses the history file and dumps it into the sql table. Which fits our intended use well enough

**Comment by conradludgate** [comment]
Currently we just use the import time if the timestamp is missing. As you said, having null fields can suck sometimes
