### ISSUE TITLE
Restore traditional ctrl+r UI

### ISSUE THREAD

**Issue by norpol** [ellie/atuin#469]
Is there a way to restore the same ctrl+r behavior as in a normal Bash/ZSH history?

The atuin UI is really nice, though I often just need this basic history because launching a full-screen TUI has some drawbacks for me such as seeing whats on the terminal, as I'd often just search for output that I've received from a previous command (like using dig to get an IP address and then typing this address to see if I can find it in my history).

**Comment by conradludgate** [comment]
See https://github.com/ellie/atuin/blob/cd2a3ab7d553f5d909f0e9412a0b4140a0c695d4/docs/key-binding.md#key-binding
