### ISSUE TITLE
interactive search drops characters when typing too fast

### ISSUE THREAD

**Issue by norpol** [ellie/atuin#471]
When I'm typing in the interactive search `atuin 0.10.0` (and possible earlier?) will frequently drop key presses.

This happens reliable after opening the interactive search and typing in something relatively quickly.

This will sometimes even happen when I'm typing in longer search words too, often times when the search is jumping across

Here is a video, on the top you can see what keys I'm pressing and on the bottom you see that atuin only registers one `p` instead of `pp`.

The behavior is much worse when my system is under high load

![recording](https://user-images.githubusercontent.com/2230917/176524255-4f919f02-13f9-4454-af46-8dc4b3143e1c.gif)

**Comment by patricksjackson** [comment]
I think that this is fixed by #448, which fixes how multiple input events are handled, and is included in v11. I tried and failed to repro this myself on v12.

Can anyone repro this on v11 or greater?

**Comment by ellie** [comment]
I'd be pretty happy to call this resolved after #448 as I also cannot repro, thanks for pointing this out.
