### ISSUE TITLE
Generate opt-in to activity graph with self-hosted atuin server

### ISSUE THREAD

**Issue by jiachengxu** [ellie/atuin#476]
Hi Ellie,

Thanks for the great work!

I have been using atuin all the time for a couple of days with a self-hosted server, and it really solves my issues of syncing shell history across different machines. I followed this session to use docker-compose to deploy my server: https://github.com/ellie/atuin/blob/main/docs/docker.md#docker-compose

Now I am trying to generate the activity graph, by executing the following command:
```bash
curl <my-atuin-server>/enable -d $(cat ~/.local/share/atuin/session)
```
and it always returns:
☕
to me. So I just want to ask: is this a feature that is only available in your atuin server or did do anything wrong?

Thanks!

**Comment by conradludgate** [comment]
Hi!

Yes, the activity graph feature is only available for the official server.

It requires access to the sync database in order to see the timestamps of your commands to be able to build the heatmap.

It's also not currently open source.

I hope you understand, and thanks for the interest in Atuin!

**Comment by jiachengxu** [comment]
Thanks for your quick answer @conradludgate! I can totally understand this!

**Comment by tieum** [comment]
I stumbled on this issue while also trying to enable the activity graph on my self hosted instance

The feature was part of why I did setup an instance, so I made one available here

https://github.com/tieum/atuin-graph

![tieum](https://user-images.githubusercontent.com/814931/236636732-d16baf32-aea2-4614-a842-1fdc24d66f68.png)

thank you for this neat tool 🙂️

**Comment by genebean** [comment]
@conradludgate just curious if you all plan to make the activity graph you run open source too.

**Comment by evanpurkhiser** [comment]
If anyone is looking for another solution for this I built this

https://github.com/evanpurkhiser/atuin-abacus

It can generates graphs like this.

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://apis.evanpurkhiser.com/atuin-abacus/graph.svg?period=1y&cellBackground=%23161b22&textColor=%23c9d1d9">
  <source media="(prefers-color-scheme: light)" srcset="https://apis.evanpurkhiser.com/atuin-abacus/graph.svg?period=1y">
  <img alt="Command History Activity Graph" src="https://apis.evanpurkhiser.com/atuin-abacus/graph.svg?period=1y">
</picture>

It also exposes a few API endpoints so you can build your own visualizations from the data. eg https://atuin-visualization.vercel.app/
