### ISSUE TITLE
feat: add option (cli or interactive input) to switch search mode at runtime

### ISSUE THREAD

**Issue by panekj** [ellie/atuin#494]
as title suggest

**Comment by conradludgate** [comment]
My search mode, do you mean prefix vs fuzzy?

**Comment by panekj** [comment]
Yes

**Comment by iamkroot** [comment]
Related- the docs incorrectly state that this is possible today (probably a copy-paste issue):

https://github.com/ellie/atuin/blob/8b9aae7076f39a1ebeecb3e2b823503f437812fa/docs/config.md?plain=1#L139-L144

**Comment by theonlydoo** [comment]
fuzzy search would be a nice improvement indeed!
