### ISSUE TITLE
Write some proper tests

### ISSUE THREAD

**Issue by ellie** [ellie/atuin#50]
Hah, what are tests?

No but seriously - now that some people actually use this (!!!) we definitely need some actual tests, beyond the super minimal set of unit tests there at the moment. 

A few end to end things that test whether or not the main features generally work would be ideal

**Comment by bl-ue** [comment]
>now that some people actually use this (!!!)

Yep, I found it just today and immediately fell in lvoe with it ❤️ 

Great work!! 🥇

**Comment by NorfairKing** [comment]
I'm happy to advise on tests: Which to write and how, but I'm not so experienced with Rust.

**Comment by ellie** [comment]
We have more tests now :)
