### ISSUE TITLE
Atuin does not sync

### ISSUE THREAD

**Issue by TheOneValen** [ellie/atuin#511]
I have two computers I want to sync. Pretty big histories. I have a selfhosted atuin server. Sync does not work, even with `--force`. Both computers have different counts of history items with `atuin stats`. I cannot see the other recent command in history on either machine after `sync` or `sync --force`. Any Idea on where I should start digging?

**Comment by ellie** [comment]
What kind of logs are you getting from the server, any errors? Any traffic at all?

**Comment by ellie** [comment]
Happy to reopen this, but for now it just seems stale
