### ISSUE TITLE
How to install atuin on Synology NAS

### ISSUE THREAD

**Issue by brucmao** [ellie/atuin#512]
I use the install script
`bash <(curl https://raw.githubusercontent.com/ellie/atuin/main/install.sh)`
```bash
Detected Linux!
Checking distro...
lsb_release could not be found, unable to determine your distribution
If you are using Arch Linux, please get community/lsb-release
```
os -verison
```
uname -a

Linux yds918 4.4.59+ #25426 SMP PREEMPT Mon Dec 14 18:48:50 CST 2020 x86_64 GNU/Linux synology_apollolake_918+


cat /etc/VERSION

majorversion="6"
minorversion="2"
productversion="6.2.3"
buildphase="GM"
buildnumber="25426"
smallfixnumber="3"
builddate="2020/12/14"
buildtime="06:14:27"
```

**Comment by conradludgate** [comment]
Seems like synology uses a package manager we're not on. If you're on x86 platform, you can download the prebuilt release: https://github.com/ellie/atuin/releases/download/v0.10.0/atuin-v0.10.0-x86_64-unknown-linux-gnu.tar.gz

**Comment by brucmao** [comment]
> Seems like synology uses a package manager we're not on. If you're on x86 platform, you can download the prebuilt release: https://github.com/ellie/atuin/releases/download/v0.10.0/atuin-v0.10.0-x86_64-unknown-linux-gnu.tar.gz

thanks for you reply, seem do not work.
```
/opt/bin# ./atuin
./atuin: /lib/libc.so.6: version `GLIBC_2.25' not found (required by ./atuin)
```

**Comment by conradludgate** [comment]
Ah, right, libc... I think you'll have to build from source then using cargo. In the readme is a section about installing with cargo

**Comment by andrewcrook** [comment]
I wonder how easy it would be to make a Synology package python , node etc are done like this.
I have also heard of people installing and using [ipkg](https://en.wikipedia.org/wiki/Ipkg) and [opkg](https://en.wikipedia.org/wiki/Opkg). I would guess opkg more so.

If you want to run server component on NAS you could use a docker image

**Comment by ellie** [comment]
> I wonder how easy it would be to make a Synology package 

If we have anyone willing to set that up + maintain it then sure!

I don't own or have access to a Synology and afaik neither does @conradludgate, so for now the only method we can really support is building from source :/
