### ISSUE TITLE
Using atuin TUI often leaves terminal in an unusable state

### ISSUE THREAD

**Issue by peterjanes** [ellie/atuin#522]
When I use the Atuin TUI (via Ctrl+R keybinding) and exit, either by selecting a command or hitting Ctrl+C, my terminal is often left in a state where it doesn't echo keypresses. I'd estimate this happens 10-20% of the time; there's no other pattern I've been able to discern.

Workaround: If I blind-type "stty sane" things go back to normal.

```
$ atuin --version
atuin 0.10.0
$ bash --version
GNU bash, version 5.1.16(1)-release (x86_64-redhat-linux-gnu)
[copyright/license blocks elided]
$ cat /etc/system-release
Fedora release 36 (Thirty Six)
```

**Comment by conradludgate** [comment]
Might be related to #492

**Comment by conradludgate** [comment]
Can you describe what "unusable state" looks like? I'll setup bash and try to replicate

**Comment by peterjanes** [comment]
I think it's a duplicate of #492 as you suggested.
