### ISSUE TITLE
Server account deletion and migration?

### ISSUE THREAD

**Issue by jesse-c** [ellie/atuin#533]
atuin looks fantastic, and I'm quite keen to try it. 2 things I've wondered though, that I haven't been able to find answers for, are:

1. Can an account be deleted on a server? E.g. the public one?
2. Can I migrate data from one server to another? E.g. the public one to my own if I started self-hosting?

Thank you!

**Comment by ellie** [comment]
Sure so

1. Currently nothing in the API, but if you drop me an email or open an issue we can sort it out

2. Make sure your client is recently synced, changed the sync server URL, and it'll sort it out for you :)

**Comment by jesse-c** [comment]
Amazing! Thank you @Ellie for the incredibly quick response.

1. Noted!
2. That's shockingly easy :)
