### ISSUE TITLE
SSH Sync

### ISSUE THREAD

**Issue by dcarosone** [ellie/atuin#54]
It would be good to have a more simple peer-to-peer sync between instances on
machines I can ssh to, e.g something like: `atuin remote {push, pull, sync} HOST`

That would basically run `ssh HOST atuin remote serve` and then do the sync
exchange over stdio rather than http. Then I can just replicate history around
machines as I log into them. Apart from not actually needing a server, this also
addresses cases where a common server isn't reachable, or would only be
reachable via setting up ssh tunnels over the same connections anyway.

The `HOST` arg of course could be `user@host`, and more complex options can be
handled with aliases in `~/.ssh/options`. In case another stdio-style transport
is added later, a `--ssh` option can be built into the command structure and 
assumed the default for compatibility.

**Comment by ellie** [comment]
This would be super cool to have! I don't think it would be particularly complex to implement either - could add `atuin export` that would basically just dump the database to stdout, and then `atuin import dump` (or similar) to read from stdin

Thank you for the suggestion :sparkles:

**Comment by ellie** [comment]
> This would be super cool to have! 

I still agree with what I said a year ago yesterday, but I don't think we will ever implement this. I'd rather focus on maintaining just one method of sync

**Comment by axelkar** [comment]
Could I have a try at implementing and possibly maintaining this? Isn't pull just cloning the server's database file and adding its unique rows to the client's own? Push is everything backwards: first cloning the server's database file, adding the client's unique rows to it and updating it back on the server (or launch a small process on the server to do it all with SQLite's lock mechanism). Please tell me if I have the wrong idea of the codebase as I haven't contributed to Atuin yet. I'm looking forward to have shell integration (perhaps automatic SSH syncing before, during(?) and after sessions) and easy commands like originally noted.

At it's easiest (not simplest):
```bash
ssh -q machine cat '~'/.local/share/atuin.db | atuin merge-database -
# Needs passwordless authentication because stdin is piped so
# that's something to fix with "easy commands" ˇˇˇ
cat ~/.local/share/atuin.db | ssh machine atuin merge-database -
```

**Comment by georgyo** [comment]
Can we re-open this, or at least reconsider it? Syncing over SSH would be far perferable to setting up a dedicated server IMHO. 

All the sync bits are already in the binary, instead of having to spin up a seperate long lived server, it could on-demand spin up the server over stdin/out and sync. This would make it much easier to run atuin sync in environments that do not have not have public network access and difficult to spin up services.

**Comment by dcarosone** [comment]
I feel like with records sync v2, this probably is even easier, and the `atuin bikeshed export | ssh host atuin bikeshed import` model will be fine for one-directional push/pull, even if it duplicates data without negotiating records already at the receiver as sync does.
