### ISSUE TITLE
[Feature] Add a non-fullscreen mode

### ISSUE THREAD

**Issue by fschoenm** [ellie/atuin#548]
The "full screen history search UI" is described as a major feature but I think there should also be a non-fullscreen mode/UI that doesn't completely block the view to what happened in the terminal. IMO it feels very unnatural to get thrown out of your normal view just to browse/search your command history. For example it's impossible to use any text or patterns that are currently shown in the terminal as part of your search query unless you remember everything.

Actually, the full screen UI is so far the main reason I couldn't get used to atuin.

**Comment by ellie** [comment]
As far as I'm aware, maintaining an actual UI without taking control of the whole terminal isn't really supported by the terminal drawing libraries we use (or any others that I could find)

If you like fzf, something like this as some sort of keybinding might suit your needs: `atuin history list --cmd-only | fzf`

**Comment by andrewcrook** [comment]
Yes I was looking for something similar like normal shell history navigation often using arrow keys but using the same source as Atuin

Discussions:
https://github.com/ellie/atuin/discussions/543

**Comment by karfau** [comment]
When I did see how `hishtory` does it I really liked it at first sight, so I put it here as an inspiration: https://github.com/ddworken/hishtory

**Comment by jean-santos** [comment]
I use atuin with fzf and works great! And it has the option to control the height.
My bash scripts looks something like [this](https://gist.github.com/jean-santos/699edaa7eda3b4315706d189223f7ac6)

**Comment by conradludgate** [comment]
Done in #648
