### ISSUE TITLE
concern: sqli (on client)

### ISSUE THREAD

**Issue by dcarosone** [ellie/atuin#55]
The assembly of SQL strings takes unprotected input from the environment / user  
context. This is on the client side (where it's less of a concern because I
already own the db file, but still):

`src/command/history.rs`:

```rust
  let session = env::var("ATUIN_SESSION")?;
  let query_session = format!("select * from history where session = {};", session);
```
I'm worried that even aside from malicious concerns, users could trip over these in normal operation. One of these queries uses `cwd` and perhaps a user has a semicolon or backtick or similar similar special character in the dir name.  (I got a little stuck on the bash integration when trying to test this; will update when I get past that).

On the server side (at a quick glance) where the input comes from the network,
it's ok; using SQLx and prepared statement bindings.

**Comment by ellie** [comment]
Closing this as the fix can be tracked in #58 

Thank you so much for both checking through the code, and taking the time to report this! :smile:
