### ISSUE TITLE
zsh history import didnt work

### ISSUE THREAD

**Issue by Anagastes** [ellie/atuin#554]
I am actively using zsh but bash is also installed).

atuin seems to get through here. Even when I explicitly specify it, it fetches the history from bash.

And completely ignores the content of the .zsh_history

Any idea to fix this? Simple rename zsh_history to bash_history? :D 

```zsh
atuin import zsh
        Atuin         
======================
          🌍          
       🐘🐘🐘🐘       
          🐢          
======================
Importing history...
Importing history from bash
Import complete!

```

**Comment by ellie** [comment]
It's a copy paste error 🤦‍♀️ 

https://github.com/ellie/atuin/blob/main/atuin-client/src/import/zsh.rs#L42

Does your ZSH shell history _actually_ get imported? Ie, if you check atuin after importing, does it contain what you'd expect?

**Comment by Anagastes** [comment]
@ellie 

Hmm, you're right. Sorry. I have now compared the databases. The contents have been merged. So it fits :D 

Sorry for my mistake. I was very confused by the output. :D
