### ISSUE TITLE
possibly a bug: install script broke my .zshrc

### ISSUE THREAD

**Issue by avinassh** [ellie/atuin#56]
Hey there 👋  This is really a nice project and just like what I needed. I did the installation using the install script, at the end my `~/.zshrc` ended up like this:

```shell
alias some_cmd="some args"eval "$(atuin init zsh)"
```

This happened because my earlier version must have not ended with a newline. May be I edited it and forgot to add a newline. I am happy to send a patch which manually adds a new line, but I was not so sure. Because this is not a bug if `~/.zshrc` files are expected to ended with a newline. Also, I am not really sure how do other install scripts behave.

**Comment by ellie** [comment]
> This is really a nice project and just like what I needed.

Thank you!

> Because this is not a bug if ~/.zshrc files are expected to ended with a newline

Nope, this is totally a bug! 

If you want to open a PR to fix this that would be awesome, otherwise I'll do it later today 😊

Thank you for reporting this!

**Comment by avinassh** [comment]
@ellie sent :D

**Comment by conradludgate** [comment]
Solved in #60 :tada: Thanks @avinassh
