### ISSUE TITLE
Atuin server with self-signed certificate

### ISSUE THREAD

**Issue by wpbrz** [ellie/atuin#570]
I tried to deploy Atuin server on my local network, placing it behind reverse proxy which adds ssl using self-signed certificate. Custom root CA which was used to sign that cert, was added to trusted certs in system store. But when I try to sync with that Atuin server I get following error:

```
$ atuin sync
Error: error sending request for url (https://atuin.xxx.xxx/sync/count): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

Caused by:
   0: error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
   1: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
```

If I try to connect using curl, everything is fine (no certificate error):

```
$ curl https://atuin.xxx.xxx
{"homage":"\"Through the fathomless deeps of space swims the star turtle Great A'Tuin, bearing on its back the four giant elephants who carry on their shoulders the mass of the Discworld.\" -- Sir Terry Pratchett","version":"11.0.0"}
```

When I display that address in browser, I can also see that cert is trusted.

How I can make Atuin to trust my custom root CA?

**Comment by conradludgate** [comment]
I think we need to configure `reqwest` to use the `rustls-tls-native-roots` feature rather than the default `rustls-tls`
https://github.com/ellie/atuin/blob/main/atuin-client/Cargo.toml#L59

**Comment by wpbrz** [comment]
Yes, after  building new version with that change, everything works fine.  I can successfully sync to the server which uses self-signed cert.

I'm a bit new to rust ecosystem and I don't know if the default value should be changed permanently or it should be  configurable, so the user can decide which one should be used when running atuin?

**Comment by ellie** [comment]
> I'm a bit new to rust ecosystem and I don't know if the default value should be changed permanently or it should be configurable, so the user can decide which one should be used when running atuin?

I'd be happy with changing the default! Using the native platform certs makes sense to me

**Comment by conradludgate** [comment]
Yes! Please submit a PR :D
