### ISSUE TITLE
Network: Connection reset by peer (os error 104)

### ISSUE THREAD

**Issue by qins** [ellie/atuin#571]
> albert@work:~$ atuin sync
> Error: error sending request for url (https://api.atuin.sh/sync/count): error trying to connect: Connection reset by peer (os error 104)
> 
> Caused by:
>    0: error trying to connect: Connection reset by peer (os error 104)
>    1: Connection reset by peer (os error 104)
> 
> Location:
>     /home/runner/work/atuin/atuin/atuin-client/src/api_client.rs:102:20

Is it because my huge history? There is about 70K lines now.

Thank you for this awesome tool!

**Comment by conradludgate** [comment]
Hmm. As far as I know you should be ok, 70K is large but not too large. Maybe try running it a few times and it might settle out?

**Comment by ellie** [comment]
I see no issues (elevated error rate/etc) on the server side, and we have historys that are much larger than that 🤔 

Can you try

`curl https://api.atuin.sh`

which should yield something like

```
{"homage":"\"Through the fathomless deeps of space swims the star turtle Great A'Tuin, bearing on its back the four giant elephants who carry on their shoulders the mass of the Discworld.\" -- Sir Terry Pratchett","version":"11.0.0"}
```

**Comment by qins** [comment]
You'r right. My bad, must be local network problem. Could not visit "Shell History" image URL neither then.

**Now working like a charm.**

![image](https://user-images.githubusercontent.com/3041080/196384299-55b66f16-7a11-4121-a2bd-f7c77362b887.png)

**Comment by qins** [comment]
> Shame your imports didn't preserve the timestamps :( I presume you use bash?

Some of my Linux equipments (about 10, all of them with bash, for compatibility) indeed has no timestamps :smiling_face_with_tear: 

Also I found atuin import my bash_history's timestamps as commands.
