### ISSUE TITLE
Performance issues using bash after installation

### ISSUE THREAD

**Issue by ndom91** [ellie/atuin#588]
First of all, great tool! Really love the concept and the available offline mode.

However, after installing, just pressing `Enter` on a blank bash shell, takes ~2-3s.

I've commented out the sourcing of the `.bash-preexec.sh` and `eval $(atuin init bash)` and its still taking multiple seconds after each command to present the next bash line, so to speak.

Any idea whats going on here?

I had `HISTSIZE=1000000` and `HISTFILESIZE=1000000`, but I've also commented that out now - no difference unfortunately.

I saw an issue related to perf on interactive search (https://github.com/ellie/atuin/issues/475), but that doesn't seem to be related. This is specifically slowing down when _not_ invoking `atuin` explicitly in any way. I assume its the hook into bash to record any commands / history items :thinking: 

Further Info:
- Arch (kernel@6.0.5)
- bash@5.1.16
- atuin@11.0.0

**Comment by ellie** [comment]
Hey! Thank you for the kind words 😊

If you are no longer running the preexec or atuin init then atuin is doing absolutely nothing with your shell - there must be something else going on

**Comment by ndom91** [comment]
> Hey! Thank you for the kind words blush
> 
> If you are no longer running the preexec or atuin init then atuin is doing absolutely nothing with your shell - there must be something else going on

Thanks for the quick response. I always just `. .bashrc` after making changes. Let me double check a few more things.

**Comment by ndom91** [comment]
So I also had `hishtory` still being sourced in my `.bashrc` (was experimenting with both haha). Reenabled the `atuin` `.bashrc` sourcing as well.

After removing that, it seems to have improved a bit, but is definitely still slower than normal.

I use `starship` as a bash prompt "theme", and it prints the cmd duration by default, and with normal "blank" `Enter`'s in bash, I'd never seen the cmd_duration be printed (it has a minimum duration of 2000ms that need to be exceed to print). And now it prints that duration on every blank `Enter` in bash.

**Comment by 3rd** [comment]
Same here on NixOS with the home-manager module, fish integration & starship. It adds a very noticeable delay before the commands are executed.

**Comment by ellie** [comment]
Hmm. How much history do you both have, @ndom91 @3rd?

I also use starship, but with zsh

**Comment by 3rd** [comment]
I had 17 entries, fresh db.

**Comment by 3rd** [comment]
I don't think home-manager does anything special, it looks ok.
It seems that it doesn't slow down the execution that much (still does) when running the same command over and over, so it should be db related, looking into it.

https://github.com/nix-community/home-manager/blob/0232fe1b75e6d7864fd82b5c72f6646f87838fc3/modules/programs/atuin.nix#L104

**Comment by ndom91** [comment]
So after a reboot (and having commented out my `HISTFILE` `.bashrc` udpates). 

It seems to have cut my histfile down to `999` entries, `~18kb`.

And now there seems to be no more noticeable lag when entering bash empty lines.

I can imagine that I had a huge `HISTFILE` previously and that might have slowed it down :thinking:

**Comment by ellie** [comment]
> And now there seems to be no more noticeable lag when entering bash empty lines.

Great!

> I can imagine that I had a huge HISTFILE previously and that might have slowed it down 🤔

Fwiw, Atuin doesn't use your HISTFILE for anything other than an initial import.

>  I always just . .bashrc after making changes. 

Otherwise, this isn't going to be clearing the old state from your shell properly + is going to result in a bunch of leftover hooks and state all running on top of each other. I'd recommend starting fresh when you're trying out new configs
