### ISSUE TITLE
cargo install outside "if cargo installed" block

### ISSUE THREAD

**Issue by ClashTheBunny** [ellie/atuin#61]
It seems like this should be moved outside of the if statement.  The if statement makes sure that cargo is installed, and after the if block, cargo will either have been installed or not needed to be installed.  https://github.com/ellie/atuin/blob/7c87624d8af033ff892bd1c21941207bcbfd3735/install.sh#L118

**Comment by bl-ue** [comment]
Agreed.

It prints `Attempting install with cargo`, but it only actually installs atuin if cargo _wasn't found_. 😄 

@ClashTheBunny great find, I'd recommend a PR 👍🏻

**Comment by ellie** [comment]
Yuup, you're correct there :woman_facepalming: Thanks for pointing this out! 

If you want to make a PR feel free, otherwise I'll get it sorted shortly :)

**Comment by ClashTheBunny** [comment]
Thanks!  I was on my phone, so it would have felt a little arrogant to try ro get it all right, tabs spaces and all.
