### ISSUE TITLE
Commands are missing under zsh

### ISSUE THREAD

**Issue by rEnr3n** [ellie/atuin#611]
```
$ atuin -V
atuin 12.0.0
```

```
$ cat ~/.config/atuin/config.toml
sync_address = "https://atuin.lan"
```

```
$ echo $SHELL
/usr/bin/zsh
```

I installed atuin and followed the shell setup for zsh: `echo 'eval "$(atuin init zsh)"' >> ~/.zshrc`
I ran a sample command to see if it's picked up by atuin. I checked the ui but it didn't. I don't have this issue on bash.

**Comment by rEnr3n** [comment]
Running `atuin search -i` gave me an error like #595. Closing the terminal did not fix it.

```
$ RUST_BACKTRACE=full atuin search -i
thread 'main' panicked at 'failed to find ATUIN_SESSION - check your shell setup: NotPresent', atuin-client/src/database.rs:30:35
stack backtrace:
0:     0x5579a7d261c3 - <unknown>
1:     0x5579a7d4a3ac - <unknown>
2:     0x5579a7d20765 - <unknown>
3:     0x5579a7d27a21 - <unknown>
4:     0x5579a7d276f3 - <unknown>
5:     0x5579a7d280c3 - <unknown>
6:     0x5579a7d27fb7 - <unknown>
7:     0x5579a7d26674 - <unknown>
8:     0x5579a7d27ce2 - <unknown>
9:     0x5579a743bf13 - <unknown>
10:     0x5579a743c063 - <unknown>
11:     0x5579a76fc389 - <unknown>
12:     0x5579a757e4e6 - <unknown>
13:     0x5579a74b6e68 - <unknown>
14:     0x5579a7521335 - <unknown>
15:     0x5579a74c6399 - <unknown>
16:     0x5579a7520fff - <unknown>
17:     0x5579a749e4d3 - <unknown>
18:     0x5579a7545f7b - <unknown>
19:     0x5579a74a2246 - <unknown>
20:     0x5579a7527e03 - <unknown>
21:     0x5579a75a7bc9 - <unknown>
22:     0x5579a7d19db2 - <unknown>
23:     0x5579a74a5068 - <unknown>
24:     0x7f467562f290 - <unknown>
25:     0x7f467562f34a - __libc_start_main
26:     0x5579a743c245 - <unknown>
27:                0x0 - <unknown>
```

**Comment by patricksjackson** [comment]
Do you still have this issue after reloading zsh?
If you source atuin directly in zsh by manually running `eval "$(atuin init zsh)"`, does it work then?

My suspicion is that the zsh session where you aren't seeing history isn't sourcing that file, either because it's not using `~/.zshrc` or because you haven't reloaded zsh.

**Comment by rEnr3n** [comment]
I tried running `eval "$(atuin init zsh)"` manually and ran a random command. I still don't see it in the ui. I also tried closing all the terminal windows. Same thing.

I tried deleting everything in `~/.local/share/atuin`. Ran one command and open the ui. This is what I see.
![2022-11-17_14:13:16+0800](https://user-images.githubusercontent.com/18730618/202370585-ff21a5ab-e37d-4166-81f7-52122f176bab.png)

**Comment by rEnr3n** [comment]
The issue was about a conflicting zsh plugin. Closing this.

**Comment by LeviticusNelson** [comment]
@rEnr3n what was the conflicting zsh plugin?

**Comment by rEnr3n** [comment]
https://github.com/jimhester/per-directory-history
