### ISSUE TITLE
comand `atuin sync` not work

### ISSUE THREAD

**Issue by theingz** [ellie/atuin#613]
When I command`atuin sync` ,prompt Error

```bash
> atuin sync
Error: encryption key is not a valid message pack encoding

Caused by:
    invalid type: newtype struct, expected Key

Location:
    atuin-client/src/encryption.rs:80:10
```

atuin key out this
```
> atuin key 
Error: could not load encryption key

Caused by:
   0: encryption key is not a valid message pack encoding
   1: invalid type: newtype struct, expected Key

Location:
    atuin-client/src/encryption.rs:80:10
```
cat key 

```
> cat ~/.local/share/atuin/key
123
```

**Comment by patricksjackson** [comment]
The encryption key isn't valid, you need to remove that key (`rm ~/.local/share/atuin/key`) and login/register again. See the docs at https://github.com/ellie/atuin/blob/main/docs/sync.md

**Comment by ellie** [comment]
As Patrick said

Otherwise, please don't post the contents of ~/.local/share/atuin/key anywhere on the internet in future, even if you think it might look wrong

**Comment by theingz** [comment]
I dont't get it.
It was still not working.
I don't understand what this key does. 
base64? or uuid?
```
> atuin sync
Error: encryption key is not a valid message pack encoding

Caused by:
    invalid type: newtype struct, expected Key

Location:
    atuin-client/src/encryption.rs:80:10
```

**Comment by ellie** [comment]
Have you tried to login or register again, after deleting the key?

>  I don't understand what this key does.

It is randomly generated by your machine and encrypts all your history so that the server cannot read it. Do not try to edit or touch this key manually

**Comment by theingz** [comment]
> Have you tried to login or register again, after deleting the key?

yes.
But it prompts me for the key

**Comment by ellie** [comment]
Please try registering again

**Comment by ellie** [comment]
When you login to a new machine, copy your key from your other machine

You can get this by running `atuin key`

**Comment by theingz** [comment]
username already in use.

```
Please enter password: 
Error: username already in use

Location:
    /home/runner/work/atuin/atuin/atuin-client/src/api_client.rs:49:9
```

**Comment by ellie** [comment]
If you already have a machine that is logged in and successfully syncing, please login again on your new machine + use the key from your functioning machine. `atuin key`


Otherwise, register an account with a new username as I cannot help with lost keys

**Comment by theingz** [comment]
Can I say: I can't get my machine back? 😢

**Comment by theingz** [comment]
> Can I say: I can't get my machine back? 😢

I mean, I forgot functioning machine's key

**Comment by theingz** [comment]
https://github.com/ellie/atuin/issues/613#issuecomment-1318792963

Need another email address

Thank you! It's working.😘

**Comment by ellie** [comment]
Yay! Glad it's sorted :raised
