### ISSUE TITLE
Can't press up arrow while running multiline command in Fish without opening atuin

### ISSUE THREAD

**Issue by khrj** [ellie/atuin#622]
Pressing <kbd>^</kbd> in fish while writing a multi line command (to go and edit the previous line) causes atuin to open.
Ideally, atuin should only open when the cursor is on the first line and <kbd>^</kbd> is pressed

**Comment by conradludgate** [comment]
That's a tricky one! I don't know enough fish to know how to deal with those keybindings

**Comment by patricksjackson** [comment]
The fix needs to just take into account the line number. You can see how fish's builtin up-or-search function does that here: https://github.com/fish-shell/fish-shell/blob/master/share/functions/up-or-search.fish

[_atuin_bind_up](https://github.com/ellie/atuin/blob/f3894ef9c0c9d2d9effa963b116d0075d4e7a9e5/src/shell/atuin.fish#L25) should lift all the logic from `up-or-search`.
