### ISSUE TITLE
Won't import anymore zsh command history after initial import

### ISSUE THREAD

**Issue by LeviticusNelson** [ellie/atuin#628]
When I run `atuin import zsh`, it imports all of my history, but I don't get any of my history of anything after doing that command. Is there something that I am missing?

**Comment by patricksjackson** [comment]
Did you follow the install instructions to set it up in your zsh config and then reload the config? https://github.com/ellie/atuin#zsh

If you are still having problems, it would help if you lay out exactly what you have tried and describe in more detail what you mean by "I don't get any of my history of anything".

**Comment by LeviticusNelson** [comment]
@patricksjackson I made sure that `eval "$(atuin init zsh)"` was added to the bottom of my .zshrc and ran `source ~/.zshrc`. I am using tmux as my environment, and I have reset tmux just to make sure. When I run the import command, I get all of my history up to the import command, but I don't think the zsh hooks are adding my executed commands after the import.

**Comment by patricksjackson** [comment]
Can you check that the preexec/precmd functions are being added? After "atuin init zsh" is evaluated you should have:

`echo $preexec_functions`  = `_atuin_preexec`
`echo $precmd_functions` = `_atuin_precmd`

I would also suggest trying the setup without your config loaded, since another plugin may be interfering. Someone else just had an issue with a conflicting plugin as well #611, though I'm not sure what exactly it was.

**Comment by LeviticusNelson** [comment]
The functions are not being added, so I will try to figure out which plugins are conflicting with this. Thanks!

**Comment by LeviticusNelson** [comment]
So I figured out that oh-my-zsh is causing the issues, I don't really need it anyways so I got rid of it. Might need to make this compatible with oh-my-zsh for others.

**Comment by conradludgate** [comment]
I'm pretty sure atuin is compatible with oh-my-zsh default install (it's very popular and I haven't heard this issue before), but oh-my-zsh makes it really easy to install plugins and maybe forget which plugins are installed

**Comment by LeviticusNelson** [comment]
@conradludgate I only had two plugins installed, and it still was causing issues even when I disabled them, so I don't exactly know what exactly was causing the issue 😂. I'd say that my .zshrc was too bloated with copy/paste configs, so I trimmed them down by a ton and have started to use [antidote](https://getantidote.github.io/) as my plugin manager rather than oh-my-zsh.

**Comment by patricksjackson** [comment]
Yea, I just tried it with a default install of oh-my-zsh. I didn't see any issues.

**Comment by LeviticusNelson** [comment]
Oh well 🤷 I thought we could find a proper fix to this issue. Lesson learned: keep your .zshrc organized.
