### ISSUE TITLE
Don't panic when the setup isn't done

### ISSUE THREAD

**Issue by jjant** [ellie/atuin#653]
I just heard of `atuin`, went to try it and got a panic:

```bash
❯ atuin
fish: Unknown command: atuin
❯ nix shell nixpkgs#atuin
❯ atuin search
thread 'main' panicked at 'failed to find ATUIN_SESSION - check your shell setup: NotPresent', atuin-client/src/database.rs:30:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The error message is clear but it'd be a bit nicer that it didn't panic.

**Comment by ellie** [comment]
Sure, we could definitely make this a bit neater!

Although, the error message does sum up what needs doing

> failed to find ATUIN_SESSION - check your shell setup: NotPresent

your shell setup is not correct

**Comment by jjant** [comment]
Yes, you're right, I edited the issue to reflect that ⭐
