### ISSUE TITLE
Very long history import time with 132k line zsh history file

### ISSUE THREAD

**Issue by bl-ue** [ellie/atuin#66]
About 17 hours ago (!), I ran `atuin import zsh`, with `$HISTFILE` set to `$HOME/.zshrc`.  My history file has 132,450 raw lines (115,029 actual entries, because of multiline commands).  Each command has the timestamp (e.g. 1600602281) and the run duration in seconds.

The format for each entry is—
```
: 1600602281:0;command --args
```

FYI—Some of the commands have strange text in (this output is from `less`): 
```
<BA>Ã<A9>© <BA>Ã<A9>®´ <BA>Ã<A9>®Ã<A9>⃨<AB>⃨<83><BA>Ã<A9>©¬©¬¨⃨<83><BA>Ã<A9>¶ <BA>Ã<A9>®Ã<A9>⃨<AB>⃨<83><BA>Ã<A9>©⃨<83><BA>Ã<A9>øcxxxxxxxjjjjjjjjjj <BA>Ã<A4>Ã<A9>⃨<AB>⃨<83><BA>Ã<A9>§⃨<83><BA>Ã<A9>© <BA>Ã<A9>®´ <BA>Ã<A9>®Ã<A9>⃨<AB>⃨<83><BA>Ã<A9>©
¬Ã<BF> <BA>Ã<A9>®Ã<A9>⃨<AB>⃨<83><BA>Ã<A9>©¬
```
It's still going.  Any way to fix this and get my 115k zsh history entries into atuin?

**Comment by ellie** [comment]
Wow I hadn't tested on anything quite that large :O Though I have about 15k and it's done in a few seconds, so it shouldn't be taking that long :thinking:

Firstly, you have the ZSH extended history format. It has to be parsed, but that shouldn't be slowing things down in an actually noticeable way. The "strange text" can result from binary being cat-ed, or can sometimes happen if your shell doesn't properly write to the file (power loss or something).

Here's the function that parses each line: https://github.com/ellie/atuin/blob/main/atuin-client/src/import/zsh.rs#L107

We batch inserts into transactions, and commit about 100 at a time. The transaction size is set here: https://github.com/ellie/atuin/blob/main/src/command/import.rs#L103

I'd planned on making that configurable, but didn't think it would ever end up being slow enough that this is required. 

Would you be able to change [this](https://github.com/ellie/atuin/blob/main/src/command/import.rs#L103) to a larger value - say, 1000 - and see how that works out?

Alternatively, perhaps the indices are slowing things down. Could definitely do with improving the logging so we can narrow things down a bit better!

Also some more information about your hardware would be fantastic. Is it an SSD?

**Comment by bl-ue** [comment]
Ooop! 🤦🏻‍♂️

@ellie I just discovered that the reason it wasn't working is because my `$HISTFILE` was set **`$HISTILE/.zsh_sessions/`** (which is a _directory_).  As soon as I changed it to `.zsh_history`, it imported quickly and beautifully. 🤣

**Comment by ellie** [comment]
Ahaha, fantastic! Could probably do with checking that $HISTFILE is *actually a file* then, but otherwise I'm glad this is sorted :)
