### ISSUE TITLE
`--disable-up-arrow` and `--disable-ctrl-r` don't work

### ISSUE THREAD

**Issue by jjant** [ellie/atuin#660]
Trying the commands from https://github.com/ellie/atuin/blob/main/docs/key-binding.md#key-binding verbatim gives an error:

```bash
❯ atuin init zsh --disable-up-arrow
error: Found argument '--disable-up-arrow' which wasn't expected, or isn't valid in this context

Usage: atuin init zsh

For more information try '--help'
```

**Comment by ellie** [comment]
Are you running the latest release, or current `main`? We actually haven't yet released that change, which I understand isn't clear from the docs

**Comment by jjant** [comment]
I'm running the latest release (v12) 🤦‍♂️ 🤦‍♂️ 🤦‍♂️
Sorry about that, I should've checked out that tag.

**Comment by mrenthu** [comment]
I also received that error when I applied this argument. Is there other way to disable Up Arrow?

**Comment by ellie** [comment]
> Are you running the latest release, or current main? We actually haven't yet released that change, which I understand isn't clear from the docs

https://github.com/ellie/atuin/blob/main/docs/key-binding.md

**Comment by aslafy-z** [comment]
@ellie Any idea when the release cut will happen? 
For the record, here's my current workaround to only enable ctrl-r binding:

```
ATUIN_NOBIND=1
eval "$(atuin init zsh)"
bindkey '^r' _atuin_search_widget
```

**Comment by ellie** [comment]
> @ellie Any idea when the release cut will happen? 
> 
> For the record, here's my current workaround to only enable ctrl-r binding:
> 
> 
> 
> ```zsh
> 
> ATUIN_NOBIND=1
> 
> eval "$(atuin init zsh)"
> 
> bindkey '^r' _atuin_search_widget
> 
> ```

Probably once the cross term stuff is in

Also fwiw - that's not a workaround, it's the documented way to do what you want. This is just neater functionality
