### ISSUE TITLE
Explicit rustup make dependency in aur pkgbuild

### ISSUE THREAD

**Issue by unai-ndz** [ellie/atuin#67]
Right now if you have rust installed using anything but `rustup` the aur helper will ask to replace it with `rustup`. To avoid this, the package should depend on `cargo` or `rust`, this way any package that provides it will work, including `rustup`. See the make dependencies of [package](https://aur.archlinux.org/packages/2048-rs/) as an example.

Diff for changing the makedeps and also adding the Upstream URL of the project:
```diff
 pkgname=atuin
 pkgver=0.6.4
 pkgrel=1
-makedepends=('rustup')
+makedepends=('cargo')
 arch=('i686' 'x86_64' 'armv6h' 'armv7h')
 pkgdesc="atuin - magical shell history"
+url="https://github.com/ellie/atuin"
 license=('MIT')
```

**Comment by ellie** [comment]
Thank you! I've just pushed an update for this to the AUR, hopefully it's ok now

**Comment by unai-ndz** [comment]
That was fast! It's fixed so I'm closing this.
