### ISSUE TITLE
Readme not showing activity graph example

### ISSUE THREAD

**Issue by razzeee** [ellie/atuin#678]
![image](https://user-images.githubusercontent.com/5943908/215364123-76a1a002-dc61-4955-8017-1abc942ee8ef.png)

**Comment by ljrk0** [comment]
Maybe we can investigate further why this doesn't work for atuin since some services still seem to work, e.g. https://github.com/Ashutosh00710/github-readme-activity-graph:

![Ashutosh's github activity graph](https://github-readme-activity-graph.vercel.app/graph?username=Ashutosh00710)
