### ISSUE TITLE
integrate with fzf

### ISSUE THREAD

**Issue by neerajbadlani** [ellie/atuin#68]
Unfortunately , I tried tui search , but still want to use fzf history search . 
I am trying to integrate with fzf using history list , it throws following error .
Can u please help ? 
Thanks 

[master:.configfiles] atuin history list
Error: environment variable not found

Location:
    src/command/history.rs:151:56

**Comment by conradludgate** [comment]
Yeah that seems to be a bug. It's looking for the `ATUIN_SESSION` environment variable, even though its not needed in your example

**Comment by ellie** [comment]
Yup the bug is with the bash script! The `ATUIN_SESSION` variable is actually needed for history to be properly recorded though, so I'll get the bash plugin fixed. 

As well as that, you'll probably want a nice way of listing *only* the command for `fzf`, so that'll need sorting too

**Comment by ellie** [comment]
Hey @neerajbadlani!

Once #89 merges, you should be able to do something like this

```
atuin h l --cmd-only | fzf
```

**Comment by neerajbadlani** [comment]
Thanks @ellie , above works and is close to what i want . However I see duplicate entries in history . 

Also , new to rust ecosystem , since brew install --HEAD dint work , so had to do manual installation . 
How do i tell rust to install in specific directory ?
```
[main:atuin] cargo install --root $(brew --prefix)
error: Using `cargo install` to install the binaries for the package in current working directory is no longer supported, use `cargo install --path .` instead. Use `cargo build` if you want to simply build the package.
```

**Comment by conradludgate** [comment]
`cargo install --path . --root $(...)` should do the trick

**Comment by neerajbadlani** [comment]
Thanks , I am able to integrate it with fzf properly now , exactly similar to what fzf provides , but with machine machine and session sync . 
2 things remaining : 1 . Duplicate Entries 2 . Sorted Histories ( Recent , Frequency , .. ) 
Should I close this and open another issue for those ?

**Comment by thedrow** [comment]
Maybe we should ask fzf's maintainers to detect if atuin is in the path and use that instead of history.

**Comment by Dentrax** [comment]
I'm looking forward to this feature! @ellie  Each time I write a command and press the <kbd>UP</kbd> key to auto-complete current cmd, TUI appears and I had a bit distracting DX. It would be great if we are able to use it with `fzf` feature enabled only. 😇 

i.e. something like the following, but `atuin` powered. :)

<img width="404" alt="Screen Shot 2021-06-12 at 13 05 18" src="https://user-images.githubusercontent.com/16493751/121772581-d7192800-cb7e-11eb-96f8-c8eb41799485.png">

**Comment by conradludgate** [comment]
@Dentrax I believe what you want is possible, although I don't know the details of how to configure the hook correctly.

This command does what you want,
```sh
atuin history list --cmd-only | fzf
```

Now, if you set `export ATUIN_NOBIND=1` in your .rc file before the atuin init step, then the TUI based hook won't be installed, and you could install your own to trigger the command I suggested above.

There's a secondary issue that atuin streaming to fzf is slow but I'm gonna close this issue as solved and open a new one for that

**Comment by hd-deman** [comment]
this thing works

```zsh
export ATUIN_NOBIND="true"
eval "$(atuin init zsh)"

zle -N _atuinr_widget _atuinr

_atuinr() {
    atuin history list --cmd-only | fzf
}
bindkey '^r' _atuinr_widget
```

The only difference is that it immediately executes the code instead of put it into the shell input. 
I don't understand how to fix it. 
any ideas?

**Comment by unai-ndz** [comment]
I have `atuin` working with `fzf` and `zsh-autosuggestions`
I don't have the time to review it now, or to publish my entire dotfiles but I can dump the important bits. Some of it is a little messy but it's decently documented.
[Pastebin](https://pastebin.com/RXxU6rT4)

@hd-deman You can write stuff into the shell input by setting it in the buffer like this: BUFFER="some stuff"

**Comment by hd-deman** [comment]
your 

> I have `atuin` working with `fzf` and `zsh-autosuggestions` I don't have the time to review it now, or to publish my entire dotfiles but I can dump the important bits. Some of it is a little messy but it's decently documented. [Pastebin](https://pastebin.com/RXxU6rT4)
> 
> @hd-deman You can write stuff into the shell input by setting it in the buffer like this: BUFFER="some stuff"

Perfect. just what I needed. Thanks

**Comment by jirutka** [comment]
There’s a better alternative to fzf written in Rust: [skim](https://github.com/lotabout/skim). Unlike fzf, it can be used as a library, so it should be relatively easy to integrate into atuin.

**Comment by panekj** [comment]
It was mentioned here already: https://github.com/ellie/atuin/discussions/286

**Comment by iloveitaly** [comment]
This doesn't work for multiline entries in the shell history. Has anyone been able to solve that?

**Comment by cocoonkid** [comment]
I found https://news.ycombinator.com/item?id=35256206

reposting here for brevity:

```
atuin-setup() {
        if ! which atuin &> /dev/null; then return 1; fi
        bindkey '^E' _atuin_search_widget

        export ATUIN_NOBIND="true"
        eval "$(atuin init "$CUR_SHELL")"
        fzf-atuin-history-widget() {
            local selected num
            setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2>/dev/null

            # local atuin_opts="--cmd-only --limit ${ATUIN_LIMIT:-5000}"
            local atuin_opts="--cmd-only"
            local fzf_opts=(
                --height=${FZF_TMUX_HEIGHT:-80%}
                --tac
                "-n2..,.."
                --tiebreak=index
                "--query=${LBUFFER}"
                "+m"
                "--bind=ctrl-d:reload(atuin search $atuin_opts -c $PWD),ctrl-r:reload(atuin search $atuin_opts)"
            )

            selected=$(
                eval "atuin search ${atuin_opts}" |
                    fzf "${fzf_opts[@]}"
            )
            local ret=$?
            if [ -n "$selected" ]; then
                # the += lets it insert at current pos instead of replacing
                LBUFFER+="${selected}"
            fi
            zle reset-prompt
            return $ret
        }
        zle -N fzf-atuin-history-widget
        bindkey '^R' fzf-atuin-history-widget
    }
    atuin-setup
```

This works really well so far!

**Comment by raghuAtRA** [comment]
> I found https://news.ycombinator.com/item?id=35256206
> 
> reposting here for brevity:
> 
> ```
> atuin-setup() {
>         if ! which atuin &> /dev/null; then return 1; fi
>         bindkey '^E' _atuin_search_widget
> 
>         export ATUIN_NOBIND="true"
>         eval "$(atuin init "$CUR_SHELL")"
>         fzf-atuin-history-widget() {
>             local selected num
>             setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2>/dev/null
> 
>             # local atuin_opts="--cmd-only --limit ${ATUIN_LIMIT:-5000}"
>             local atuin_opts="--cmd-only"
>             local fzf_opts=(
>                 --height=${FZF_TMUX_HEIGHT:-80%}
>                 --tac
>                 "-n2..,.."
>                 --tiebreak=index
>                 "--query=${LBUFFER}"
>                 "+m"
>                 "--bind=ctrl-d:reload(atuin search $atuin_opts -c $PWD),ctrl-r:reload(atuin search $atuin_opts)"
>             )
> 
>             selected=$(
>                 eval "atuin search ${atuin_opts}" |
>                     fzf "${fzf_opts[@]}"
>             )
>             local ret=$?
>             if [ -n "$selected" ]; then
>                 # the += lets it insert at current pos instead of replacing
>                 LBUFFER+="${selected}"
>             fi
>             zle reset-prompt
>             return $ret
>         }
>         zle -N fzf-atuin-history-widget
>         bindkey '^R' fzf-atuin-history-widget
>     }
>     atuin-setup
> ```
> 
> This works really well so far!

Works really well - but how do I get the preview window? I tried adding `                "--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"` to the `fzf_opts` but that doesn't change anything.

**Comment by nicoandmee** [comment]
> Has anyone been able to get this working properly with multiline shell history? If there's a history command that is multiline, it shows up as multiple entries in the fzf list, which makes this fzf-based search unusable :(

Also wondering this

**Comment by conradludgate** [comment]
#1274 which should be out next week should help with that

**Comment by alcroito** [comment]
> > This works really well so far!
> 
> Works really well - but how do I get the preview window? I tried adding ` "--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"` to the `fzf_opts` but that doesn't change anything.

This worked for me

```zsh
        local fzf_opts=(
            --height=${FZF_TMUX_HEIGHT:-80%}
            --tac
            "-n2..,.."
            --tiebreak=index
            "--query=${LBUFFER}"
            "+m"
            '--preview=echo {}'
            "--preview-window=down:3:hidden:wrap"
            "--bind=?:toggle-preview"
            "--bind=ctrl-d:reload(atuin search $atuin_opts -c $PWD),ctrl-r:reload(atuin search $atuin_opts)"
        )

```

**Comment by pejaab** [comment]
Regarding fish I ended up creating a new key binding in the function reserved for this: `fish_user_key_bindings` in `.config/fish/functions`.
The the key binding or better the function looks like the following:
```
function fish_user_key_bindings
  bind -M insert \cR 'atuin search --cmd-only | fzf'
end
```
`-M insert` is required in my case as I'm relying on `fish_vi_key_bindings` and might not be needed in your case.

**Comment by shkm** [comment]
> > Does anyone have fzf working with atuin and fish? It seems like that script is zsh only.
> 
> Regarding fish I ended up creating a new key binding in the function reserved for this: `fish_user_key_bindings` in `.config/fish/functions`. The the key binding or better the function looks like the following:
> 
> ```
> function fish_user_key_bindings
>   bind -M insert \cR 'bind -M insert \cR 'atuin search --cmd-only | fzf -q (commandline)'
> end
> ```
> 
> `-M insert` is required in my case as I'm relying on `fish_vi_key_bindings` and might not be needed in your case.
> 
> This probably can be tweaked further, but should be a good starter.
> 
> UPDATE: I actually realized that the above doesn't work as I expected, particularly not setting the selected command to be modified or properly used. I finally found how to do this properly, I think:
> 
> ```
> function _atuin_fzf_search
>   set -f commands_selected (
>     atuin search --cmd-only |
>       _fzf_wrapper --print0 \
>         --query=(commandline) \
>   )
> 
>   if test $status -eq 0
>       commandline --replace -- $commands_selected
>   end
> 
>   commandline --function repaint
> 
> end
> 
> function fish_user_key_bindings
>     bind -M insert \cR _atuin_fzf_search
> end
> ```

Thanks for this. I needed to use `atuin search --cmd-only --reverse` to get the fzf results in the correct order.

**Comment by bakai-taalaibek** [comment]
This is my fish function
```
function fzf_history
    set -l line (commandline)

    # tac reverses order initially, tiebreak sorts(?), -n2..,.. ignores first two fields, +m means no "--multi"
    set -l result (atuin search --cmd-only | fzf --tac "-n2..,.." --tiebreak=index "+m" --query="$line")

    set -l key $result[1]
    set -l selected $result[2]

    if test "$key" = enter
        commandline --replace $selected
        commandline -f repaint
        commandline -f execute
        return
    end

    if test -n "$selected"
        commandline -r -- $selected
    end

    commandline -f repaint
end
```
my fzf defaults:
```
set -gx FZF_DEFAULT_OPTS "--bind=alt-k:up,alt-j:down --expect=tab,enter --layout=reverse 
  --height=17 --delimiter='\t' --with-nth=1 
  --color=fg:#646464,fg+:#5d5a5a,bg:#fafafa,bg+:#dcdcdc
  --color=hl:#66ac60,hl+:#498743,info:#a49472,marker:#87ff00
  --color=prompt:#00bdd6,spinner:#a49472,pointer:#599eff,header:#87afaf
  --color=gutter:#fafafa,border:#b6b6b6,separator:#c6c6c6,scrollbar:#67625e
  --color=preview-fg:#434343,label:#afafaf,query:#6f6f6f
    --preview-window='border-rounded' --prompt='  ' --marker=' ' --pointer=' ' 
    --separator='─' --scrollbar='┃' --layout='reverse' 
  "
```
