### ISSUE TITLE
atuin import fish on macOS: Could not find history file

### ISSUE THREAD

**Issue by otaconix** [ellie/atuin#682]
# Reproducing the issue

```shell
$ atuin import fish
```

# Expected outcome

```
        Atuin
======================
          🌍
       🐘🐘🐘🐘
          🐢
======================
Importing history...
Importing history from fish
█████████████████████████████████████████████████████████ x/x Import complete!
```

# Actual outcome

```
        Atuin
======================
          🌍
       🐘🐘🐘🐘
          🐢
======================
Importing history...
Importing history from fish
Error: Could not find history file.

Location:
    atuin-client/src/import/fish.rs:39:13
```

# Extra information

Atuin uses the [`directories`](https://crates.io/crates/directories) crate to determine where to search for the fish history file, and it (rightfully) looks in `~/Library/Application Support/fish`. Fish stores its data in `~/.local/share/fish`, even on a mac.

# Workaround

If you need to import your fish history on macOS, simply copy/symlink your `fish_history` to the "right" place:

```shell
$ mkdir "~/Library/Application Support/fish"
$ ln -s ~/.local/share/fish/fish_history "~/Library/Application Support/fish/" # If you need to import another session, make sure to change this command
$ atuin import fish
```

**Comment by conradludgate** [comment]
Ah, thanks for spotting. I feel like we're always going to fight file locations. I believe there's an environment variable that should let you override without a symlink. But it seems it never got the change to write the error. I'll look into that

**Comment by conradludgate** [comment]
Found the issue.

https://github.com/ellie/atuin/blob/893a395f12d29b6b6676db3672fb7e600c49aff7/atuin-client/src/import/fish.rs#L49

This should be using our `get_histpath` utility.
```rust
let path = get_histpath(default_histpath)?;
let mut f = File::open(path)?;
```

**Comment by charego** [comment]
> Atuin uses the [directories](https://crates.io/crates/directories) crate to determine where to search for the fish history file, and it (rightfully) looks in ~/Library/Application Support/fish. Fish stores its data in ~/.local/share/fish, even on a mac.

In my opinion fish does this right, and atuin should do the same, i.e. not use the directories crate for this.

@ellie seems to agree based on [this comment](https://github.com/ellie/atuin/blob/v12.0.0/atuin-common/src/utils.rs#L11-L12):

```rust
// I don't want to use ProjectDirs, it puts config in awkward places on
// mac. Data too. Seems to be more intended for GUI apps.
```

I made a pull request for this: https://github.com/ellie/atuin/pull/601

**Comment by alper** [comment]
Thanks for the workaround!

**Comment by ijanos** [comment]
Heyo, I just ran into this and the fix PR was closed without being merged, was that intentional? Any issues with that PR? I'm happy to make a new one if needed.

**Comment by charego** [comment]
I closed it due to inactivity. @ijanos feel free to take the changes and create a PR yourself.

**Comment by ellie** [comment]
> I closed it due to inactivity. 

Sorry. Had a pretty busy year last year :/ Happy to take a look if you reopen it

**Comment by charego** [comment]
No worries! I didn't mean it as a complaint. This is open source, after all.
