### ISSUE TITLE
\termion-1.5.6\src\lib.rs:24:9    | 24 | pub use sys::size::terminal_size;    |         ^^^ maybe a missing crate `sys`?

### ISSUE THREAD

**Issue by jinfagang** [ellie/atuin#685]
\termion-1.5.6\src\lib.rs:24:9
   |
24 | pub use sys::size::terminal_size;
   |         ^^^ maybe a missing crate `sys`?

**Comment by ellie** [comment]
Sorry, I'll need a bit more information to help here

1. what system are you building on? (os, etc)
2. what version of rust are you trying to use?
3. what command are you running to get this error?
4. what have you already tried to resolve it?

**Comment by jinfagang** [comment]
windows11, rust latest, cargo install atuin

**Comment by conradludgate** [comment]
@jinfagang We don't have any official support for windows yet, and `termion` is not at all compatible.

We have a branch that should be merged soon using `crossterm` which does have windows support. It's possible it might work but we can't guarantee it for now. You can try it by running
```sh
cargo install --locked --git https://github.com/ellie/atuin --branch crossterm
```

I think in future @jean-santos offered to help test windows support for us, but we still can't guarantee it will be maintained long term

**Comment by jinfagang** [comment]
@conradludgate thanks, as more and more people are using powershell nowadays, it could be good invest on preparing support windows. (these paths or bins shouldn't be a big problem, might can have vairous system host when aync though) I really hoping there could be a stable windows support.

**Comment by conradludgate** [comment]
I agree it would be nice. It's been on our radar for a long time now (#135), but we don't yet have a maintainer that can test on windows regularly.

As I said, we might soon accidentally support windows. So I would be happy to consider PRs that add powershell support, especially as powershell is seeing some popularity on nix systems.

**Comment by conradludgate** [comment]
So it's not a "no we will never support windows", but more that "it's not something we can do right now"
