### ISSUE TITLE
NuShell support

### ISSUE THREAD

**Issue by ellie** [ellie/atuin#687]
We investigated doing this a while ago: https://github.com/ellie/atuin/pull/182

At the time, NuShell did not have the hooks we needed. But it sounds like now it does!

https://twitter.com/jntrnr/status/1622274570651865090?s=20

**Comment by xbladesub** [comment]
Thank you for this very cool tool. How can we configure atuin for the nushell?

**Comment by conradludgate** [comment]
Sounds ok to me

**Comment by ellie** [comment]
I'd rather stick to having the command put in the start by default, though I'm open to filling it in as part of `end`. My concern there is just that if we have a `start` that never calls `end`, we end up with a bunch of empty history.

If there's no other way, then it would be acceptable! I'll jump on their Discord and see if we can push on it a little more

**Comment by ellie** [comment]
Turns out @stevenxxiu has been working on that feature for NuShell! https://github.com/nushell/nushell/pull/8207

Thank you so much - can't wait to get that support out!

**Comment by patricksjackson** [comment]
Oh! I thought https://github.com/nushell/nushell/pull/8207 was just some early work, but it looks farther along. Awesome :)

Probably not worth it to implement my proposed hacky workaround unless something else needs it in the future.

**Comment by ellie** [comment]
Let's wait - worst case we can fallback on your workaround!

**Comment by YummyOreo** [comment]
> Cool tool -- found it yesterday when I was looking to replace fzf-in-zsh for command history. I recently started using nushell, so followed the instructions to integrate. I'm new to nushell as well, but apparently the syntax for ranges has changed/is changing? I'm running nushell 0.78.1, built from source, and when I select an item in atuin I get:
> 
> 
> 
> ```
> 
> Error: nu::shell::cant_convert
> 
> 
> 
>   × Can't convert to range.
> 
>    ╭─[entry #1:1:1]
> 
>  1 │ # 9f6f3001-2271-4a1e-bd21-8707aeda4a23
> 
>  2 │ commandline (RUST_LOG=error run-external --redirect-stderr atuin search "--shell-up-key-binding" "--interactive" "--" (commandline) | complete | $in.stderr | str substring ',-1')
> 
>    ·                                                                                                                                                                             ──┬──
> 
>    ·                                                                                                                                                                               ╰── can't convert string to range
> 
>    ╰────
> 
> ```
> 
> 
> 
> If I change that part in line 33 of the generated `init.nu` to `str substring ..-1` then it works. 
> 
> 
> 
> Great tool -- thanks for your work!

This should already be fixed in #840
