### ISSUE TITLE
Sodiumoxide has been deprecated, could age be used instead? 

### ISSUE THREAD

**Issue by mangas** [ellie/atuin#702]
Deprecated:
https://github.com/sodiumoxide/sodiumoxide

Age: 
https://github.com/FiloSottile/age

Spec:
https://github.com/C2SP/C2SP/blob/main/age.md

Rust implementation:
https://github.com/str4d/rage

**Comment by ellie** [comment]
If age supports SecretBox, then yes. Otherwise no :/ 

Realistically we will switch to using RustCrypto. Not a huge priority right now as while Sodiumoxide has been deprecated, it does still receive security updates

**Comment by mangas** [comment]
It supports symmetric encryption and it's a more modern standard as well. If there is some work to introduce events and deletion, there could be a field on the DB to choose the type of encryption as a migration path.

**Comment by conradludgate** [comment]
Yeah the current plan is to switch to https://github.com/RustCrypto/nacl-compat to remain backwards compatible
