### ISSUE TITLE
Maybe include "open a new shell session" in the documentation

### ISSUE THREAD

**Issue by myz-dev** [ellie/atuin#703]
Hi,

I just had trouble running `atuin` after I followed the steps in the read-me. I was stupid enough to try running `atuin search xx` in the same session in which I ran the eval init command (after installing with the recommended script).  So I kept getting `thread 'main' panicked at 'failed to find ATUIN_SESSION` error messages.
Maybe in the `install` section after `And then follow [the shell setup](https://github.com/ellie/atuin#shell-plugin)` there could be a note like "and do not forget to open a new shell before you run `atuin search ls`".

**Comment by conradludgate** [comment]
In principal, any time you modify your shell scripts, you must `source path_to_init` to reload your shell features to load in the new plugins.

We could add a line that says this, definitely. I think we assumed it was obvious 🤦

**Comment by ellie** [comment]
Corrected! Thank you for the suggestion
