### ISSUE TITLE
up-key filtermode session does not work

### ISSUE THREAD

**Issue by clotodex** [ellie/atuin#710]
`filter_mode_shell_up_key_binding = "session"` still applies global filter, also when explicitly set in config

- shell: `fish`
- autin: `12.0.0`
- setup: `default` (source and default config with this setting)

Do I need to set up something specific for this or did I misunderstand something?

**Comment by ellie** [comment]
Hey! This is currently only available if running the latest `main`, and is not in v12. It will be in v13, which I'd like to release pretty soon - there's just a couple things I'd like to fit into it first! Including crossterm, which landed yesterday
