### ISSUE TITLE
update database on the fly when scrolling up on interactive search

### ISSUE THREAD

**Issue by kiteloopdesign** [ellie/atuin#726]
Hi,
Playing a bit with atuin, I see that when I do
`atuin search -i` I can only scroll so far up until no more lines are show. I would say I can scroll up to 200-300 lines (difficult to tell as they are not numbered)

I know there are way more lines as doing all these things work

```
atuin history list | wc
  18656  119677  960770
```

or

```
atuin stats
+---------------------+-------+
| Statistic           | Value |
+---------------------+-------+
| Most used command   |     l |
+---------------------+-------+
| Commands ran        | 18262 |
+---------------------+-------+
| Unique commands ran | 16570 |
+---------------------+-------+
```

I think it should be expected that the user can scroll up indefinitely ? (I guess you will need to query the db on they fly, which probably you are not doing ...)

**Comment by ellie** [comment]
Is there any reason you need to scroll up so far, and can't search for what you want?

Considered implementing this but it feels like a UX antipattern to me

**Comment by kiteloopdesign** [comment]
Hmm, interesting, it does feel super natural to me to what to have a look at what happened at some time. Its just going back in time, nothing too fancy. But i understand it may be a problem since you may not have that info pulled locally...

**Comment by conradludgate** [comment]
We do indeed limit interactive search to 200 entries. There's no hard limit here but we're more concerned with having a snappy UI rather than loading all the data.

We could implement a lazy paging system to load more, but it doesn't make the most sense IMO.

If you don't mind the effort, you can always use the sqlite db manually, or build your own custom interface. I'm not sure if I quite see the usecase for atuin currently. If you have a convincing usecase for why you need to see all your history I'd happily reconsider

**Comment by conradludgate** [comment]
> But i understand it may be a problem since you may not have that info pulled locally...

The client operates under the assumption that all history items are pulled locally (if they are not, they will soon enough) so that's not an issue here. All history items are stored locally first. The sync server is just a backup sync service

**Comment by ellie** [comment]
I really don't want to encourage users to page through their history a line at a time - really, `atuin history list` is perfect for this. Even `atuin history list | less`

I'd rather avoid adding even more complexity to our UI to enable behaviour I do not want to encourage

Happy to take arguments for this, but atm I don't see it
