### ISSUE TITLE
Can't filter on dot (.) characters

### ISSUE THREAD

**Issue by peterjanes** [ellie/atuin#735]
I can't seem to filter on strings containing a `.` character.

Test case:

```
history_filter = [
  "..."
]
```

Expected result:

Any history entry longer than 3 characters should be filtered.

OR

Any history entry containing `...` should be filtered.

Actual result:

No change in the presented history.

Notes:

The `.` doesn't appear to be recognized as a regex wildcard—with the config above I'd expect any command longer than 3 letters to be filtered—but it also doesn't match strings containing the literal `...` characters, e.g. `ls /tmp/.../foo` is still returned.

I've tried escaping the `.` characters as well, e.g. `"\\.\\.\\."`, but that doesn't make any difference. (`"\.\.\."` is invalid TOML.)

(Using the newly-released atuin 13.0.0 to test.)

**Comment by bvergnaud** [comment]
Hi 👋🏻 

I might be over-interpreting but based on the wording of your message, I think you might have misunderstood the function of this option. It does not filter what the history shows you, but rather what gets recorded in the first place. Any entry already in your history will stay there, but new entries will not be recorded if they match one of your regexes.

That being said, I've been playing with this option for a bit this evening without any hiccups so far. And I just tested your suggestion, and it seems to have the desired effect. With `"..."` in the list, `ls` is recorded in my history, `"echo"` is not.

**Comment by peterjanes** [comment]
You're right, I misinterpreted the option. (I thought it was related to the upcoming delete feature mentioned in the release notes.) It does behave as you've described: the complete existing history is treated as it always was, but new commands matching the filters aren't added.
