### ISSUE TITLE
Can't create user on local server

### ISSUE THREAD

**Issue by maxim-rapidapi** [ellie/atuin#739]
Server is configured to use remote database:

```
## host to bind, can also be passed via CLI args
host = "0.0.0.0"

## port to bind, can also be passed via CLI args
port = 8888

## whether to allow anyone to register an account
open_registration = true

## URI for postgres (using development creds here)
db_uri="postgres://atuin:something@my.pg.host/atuin"
```

On the client, I have `sync_host = "http://atuin.host.blah:8888"`, and I always get this error message on the server. Error 500 could be anything, of course ;)

```
2023-02-28T15:18:48.599027Z ERROR tower_http::trace::on_failure: response failed classification=Status code: 500 Internal Server Error latency=0 ms
```

The client tells me 
```
Please enter username: myuser
Please enter email: mymail@domain.com
Please enter password:
Error: error decoding response body: expected value at line 1 column 1

Caused by:
    expected value at line 1 column 1

Location:
    /private/tmp/atuin-20230226-5951-12mg7e/atuin-13.0.0/atuin-client/src/api_client.rs:62:21
```

The schema in the database is created upon server start, so the database connection works. I have tried to use the client on MacOS (arm64), and arm64 and x86_64 Linux, but the result is always the same.

 Any pointers to solving this greatly appreciated!

**Comment by conradludgate** [comment]
Yep, sorry, this is a bug with the v13 server. Got a PR up to fix it. I think we can cut a v13.0.1 shortly. For now you could try run a v12 server, it should work just fine as we haven't added any server-side changes in the last release
