### ISSUE TITLE
Document MSRV

### ISSUE THREAD

**Issue by cyqsimon** [ellie/atuin#746]
I'm working on a patch for #745 right now and could really benefit from the `let ... else` construct, which was stabalised in Rust 1.65.0. But I don't know if I can use it because there seems to be no MSRV policy.

Please consider adding an official policy (`CONTRIBUTING.md`?), thanks.

**Comment by conradludgate** [comment]
We are currently using latest stable as our rust version. We make no promises on a minimum supported rust version

**Comment by cyqsimon** [comment]
> We are currently using latest stable as our rust version.

Thanks, that's good to know. I still think it would be useful if you could put this information in README.
