### ISSUE TITLE
Missing docker image for ARM

### ISSUE THREAD

**Issue by ealap** [ellie/atuin#751]
Since v13.0, docker image for ARM seems to be missing

```
$ docker pull ghcr.io/ellie/atuin:12.0
12.0: Pulling from ellie/atuin
Digest: sha256:9e20849cb256337ef7c8df8986f106bf0691675189e98a3c805d1554f5e7ca19
Status: Image is up to date for ghcr.io/ellie/atuin:12.0
ghcr.io/ellie/atuin:12.0

$ docker pull ghcr.io/ellie/atuin:13.0
13.0: Pulling from ellie/atuin
no matching manifest for linux/arm64/v8 in the manifest list entries

$ docker pull ghcr.io/ellie/atuin:main
main: Pulling from ellie/atuin
no matching manifest for linux/arm64/v8 in the manifest list entries
 
```

**Comment by ellie** [comment]
Yup, unfortunately we've had to disable them for now. They've only been in since November, and it looks like they struggle to link properly 

I'm hoping once we are entirely Rust code this will no longer happen, but it's probably coming from a C dependency

**Comment by ellie** [comment]
Sorry for the ops hassle! :/

> Hopefully, compatibility won't break between my server and client before the fix 😅

It won't do - we still have a lot of people using old releases, even back to 0.7! So the old sync methods will be supported for a long time yet.

**Comment by ellie** [comment]
Just a heads up that we now build on arm, thanks to https://actuated.dev!
