### ISSUE TITLE
`filter_mode` configuration does not seem to have any effect

### ISSUE THREAD

**Issue by sdroege** [ellie/atuin#756]
I have the following in  `~/.config/atuin/config.toml`

```toml
filter_mode = "directory"
```

I think this worked correctly in atuin 12 but doesn't anymore in atuin 13. Now the history always defaults to `global` and needs to be changed via ctrl+r.

**Comment by rEnr3n** [comment]
It did work on v12. No changes on configuration were made when it broke.

**Comment by ellie** [comment]
Hey! I think this was introduced in #635 

We now allow configuring the filter mode for up, and the mode for ctrl-r separately, so atm setting just `filter_mode` will not change both. 

Setting this in your config:
```
filter_mode = "directory"
filter_mode_shell_up_key_binding = "directory"
```

Should resolve the issue. Will get this fixed for the next release! `filter_mode_shell_up_key_binding` should default to whatever `filter_mode` is, and not `global`.

**Comment by sdroege** [comment]
Thanks, that was the problem :)
