### ISSUE TITLE
Unable to paste on search

### ISSUE THREAD

**Issue by vitorcoxta** [ellie/atuin#786]
Hey there!

I recently updated atuin to the most recent version at the moment, v13.0.1, and noticed an issue that I didn't had in the older version I had (which honestly I don't know what was it). When querying commands hitting Crtr-R, I'm no longer able to paste any text.

I've been pasting text there all the time, it's pretty useful for me. Can you please have a look into this?

Thank you in advance!

**Comment by conradludgate** [comment]
Yes, I think you are right. We switched terminal backend implementation from `termion` to `crossterm`. crossterm has a [specific event for paste](https://docs.rs/crossterm/0.26.1/crossterm/event/enum.Event.html#variant.Paste) which termion doesn't have, I suspect that termion is just interpreting them as keypresses.

It shouldn't be too hard to add support for the paste event

**Comment by vitorcoxta** [comment]
Thank you @conradludgate ! Looking forward to that support!
Great work by the way! 💪

**Comment by ellie** [comment]
Thank you! I've assigned it - please let us know if you need any help!
