### ISSUE TITLE
Docs: Add contribution guidelines with a way to have a sandboxed development environment

### ISSUE THREAD

**Issue by RafaelKr** [ellie/atuin#800]
I installed atuin today and I love it!

I wanted to tackle issue #78. For that I cloned the repo and tried to run the project in my IntelliJ IDEA in debug mode (The command `run --package atuin --bin atuin -- search --interactive` should do it).

Probably I should have checked out a stable commit like e4fde80a (v13.0.1) first, but instead I tried to do the process on main branch.

Unfortunately in the process my atuin install broke and I ~get~ got the following error, also when running it from the normal terminal now. ~Is there a way to fix this? I also wouldn't mind if I had to remove the history and reimport it from zsh as I only started today.~

```
Error: migration 20230315220114 was previously applied but is missing in the resolved migrations

Caused by:
    migration 20230315220114 was previously applied but is missing in the resolved migrations

Location:
    src/command/client.rs:50:22
```

I fixed this by deleting `~/.local/share/atuin` and importing my zsh history again. It didn't matter as only the history from today is lost.

I couldn't find a [CONTRIBUTING.md](https://en.wikipedia.org/wiki/Contributing_guidelines) or a Contributing section in the docs at [atuin.sh](https://atuin.sh/). it would be helpful to have an explanation how to setup a development environment, in the best case "sandboxed" from the real environment, so a developer can't destroy his history 😊

**Comment by conradludgate** [comment]
Yeah, a few people have asked us for one, @ellie and I agreed yesterday that it would be a good thing. Will get that done soon.

As for your issue, you'll need to fully install atuin from the `main` branch. This is the first time we've properly ran a client-side DB migration so we weren't sure what friction we'd expect, sorry about that.

If you installed atuin from a package manager, I'd suggest uninstalling, then run `cargo install --path .` from the main branch and it will re-install with the migration applied. We intend to get V14 out in a week or two, then you can re-install as you wish

**Comment by ellie** [comment]
> so a developer can't destroy his history 😊

or her history 😊 

https://github.com/ellie/atuin/blob/main/CONTRIBUTING.md

There you go! I don't generally sandbox other than running a different user for testing sync - I find it way more useful to test with "real" data.

**Comment by RafaelKr** [comment]
> > so a developer can't destroy his history blush
> 
> or her history blush

Of course! Updated.

> 
> [`main`/CONTRIBUTING.md](https://github.com/ellie/atuin/blob/main/CONTRIBUTING.md?rgh-link-date=2023-03-26T17%3A33%3A06Z)
> 
> There you go! I don't generally sandbox other than running a different user for testing sync - I find it way more useful to test with "real" data.

That was fast, thanks! Using an own user is of course a very nice way :) Do you switch the system user for that or do you use some `su`-magic?

I now found a different way I'll use:
1. I created `/home/rafael/.config/atuin/atuin-dev`
2. I did copy the default config.toml to that path
3. I set `db_path = "~/.config/atuin/atuin-dev/history.db"` in that file
4. I copied my history.db to that directory
5. I run my cargo commands with ATUIN_CONFIG_DIR=/home/rafael/.config/atuin/atuin-dev

Works like a charm! :blush:

**Comment by ellie** [comment]
That also works very well! I like it :D Would you be open to make a PR to add it as an option in the docs?

I `su` into a different user generally, and only really when I want to test sync

**Comment by RafaelKr** [comment]
I'll see if I can find the time for that sometime this week :)
