### ISSUE TITLE
Skim (not a issue )

### ISSUE THREAD

**Issue by RaWolFoX** [ellie/atuin#837]
What's the difference between fuzzy and skim. What is the benefit of skim over fuzzy?.I didn't really understand. Sorry for posting as a issue.

**Comment by shymega** [comment]
@RaWolFoX There is a 'Discussions' tab, not sure if you're aware, but that's best placed for questions like this. If Ellie or Conrad want to, they could convert this issue into a discussion. It's quite a cool feature, the Discussions tab, very useful for questions like yours.

**Comment by ellie** [comment]
They're different implementations of a similar thing, and "feel" different. Try them and see what you think!

We've released it as a bit of an experiment here, just to see whether it tends to behave better or worse

**Comment by RaWolFoX** [comment]
> @RaWolFoX There is a 'Discussions' tab, not sure if you're aware, but that's best placed for questions like this. If Ellie or Conrad want to, they could convert this issue into a discussion. It's quite a cool feature, the Discussions tab, very useful for questions like yours.

👍🏻

**Comment by RaWolFoX** [comment]
How to just search exact word. Like if i search cd its shows all cd with long commands but insted just show cd only. How to do that😐🤔
