### ISSUE TITLE
Please add a compile-time flag to disable update_check

### ISSUE THREAD

**Issue by alerque** [ellie/atuin#846]
When installed from a distro package manager that the user is not in control of and will likely be updated by the distro anyway, the default true update_check is really annoying. Also some people consider it a privacy risk/violation.

Please add a built-time flag to either disable the feature or set the default value to false that distro packagers can use to turn it off for systems where updating isn't up to the end user as much as it is when installed directly from sources.

cc: @orhun

**Comment by conradludgate** [comment]
This exists already. `cargo install --no-default-features --features client` will install the bare minimum client with no networking features. We do not control how they are packaged up, so feel free to install from source

**Comment by alerque** [comment]
I don't want to disable all networking features. I want to keep using my self hosted server. The only thing I don't want is the update ping/notification.

**Comment by orhun** [comment]
Is it possible to disable the update_check feature without disabling networking?

**Comment by ellie** [comment]
It is!

`update_check = false` in your config file

**Comment by alerque** [comment]
Disabling this in my own RC files is different that disabling it by default for some types of installs. If an end user downloads the source or a binary and puts in in their `~/bin` or `/usr/local/bin` I might expect and auto-update check to function. But for software installed through a distro package manager update checks are generally counter-productive. The user usually doesn't have control over when their distribution's package gets bumped, and when it does they will generally get the update along with lots of other system updates. When installed from a distribution's package manager individual programs should not all be pinging home by default checking for updates.

The config file flag for `update_check` is not what this issue was about, I would like to see a *compile time* option to disable the update-checker by default (without neutering the sync or other network functions of the client).
