### ISSUE TITLE
When selecting command from history Nushell throws an error

### ISSUE THREAD

**Issue by PhilVince96** [ellie/atuin#852]

**Comment by ellie** [comment]
Hey! Just a few questions so we can better help you

1. What error are you getting?
2. What version of Atuin are you running?
3. What version of NuShell are you running?

We require the very latest version of NuShell

**Comment by PhilVince96** [comment]
Sorry, I meant to give a more detailed description of the error. Had a problem with the GitHub iOS app.

Error:
![IMG_0260](https://user-images.githubusercontent.com/29581161/230315968-55cf0cbf-22f8-4b2c-941c-ad13920c34e9.jpeg)

Atuin Version: 14.0.0

Nushell Version: 0.78.0

**Comment by PhilVince96** [comment]
![IMG_0261](https://user-images.githubusercontent.com/29581161/230317132-eecb37cd-571a-4b9c-bce7-722c03799469.jpeg)

Maybe the error is caused by this breaking change from Nushell 0.77.2 to 0.78.0.?

**Comment by PhilVince96** [comment]
It solved the problem as I changed this line in the ~/.local/share/atuin/init.nu file. Thanks! 😊
