### ISSUE TITLE
Config setting `inline_height` is not respected.

### ISSUE THREAD

**Issue by peterbraden** [ellie/atuin#855]
I've set the config inline_height:

<img width="419" alt="Screenshot 2023-04-07 at 15 17 35" src="https://user-images.githubusercontent.com/52586/230615598-546c8fad-c002-4e23-8ce0-82deb2b333aa.png">

But triggering atuin with the up key still shows the full screen interface:

<img width="546" alt="Screenshot 2023-04-07 at 15 17 54" src="https://user-images.githubusercontent.com/52586/230615674-26d2c8e4-2128-41f4-a952-1f453986fdec.png">

I believe this should be limited in size?

Context:
- in tmux in iterm with zsh.
- atuin 13.0.1

**Comment by ellie** [comment]
You’ll need to run atuin v14 for this to work
