### ISSUE TITLE
Have `login` check for current session

### ISSUE THREAD

**Issue by ClashTheBunny** [ellie/atuin#86]
It would be nice if login would print that "You're already logged in with a valid session token" if already logged in.  Maybe either have a command or option to log out, or a `[Y/n]` question to log out if logged in.

**Comment by conradludgate** [comment]
Personally, I think I'd prefer if it silently exited without logging in again if there's already a session file. Perhaps also providing a `logout` command to easily delete the session file

**Comment by ellie** [comment]
I'd prefer to go for the approach of having a `logout` command, and making login bail with a message if there's already a session token. 

Checking if the session is actually valid would require us to hit `count` or some other authed endpoint to ensure validity, but I don't think this is entirely necessary. Users could just logout and then login again if there are any problems (say, we need to roll all session tokens)
