### ISSUE TITLE
Remove program name and version in compact style

### ISSUE THREAD

**Issue by misuzu** [ellie/atuin#887]
Could this be removed or at least be configurable?
<img width="423" alt="Знімок екрана 2023-04-16 о 20 56 18" src="https://user-images.githubusercontent.com/248143/232332221-84185d2b-637b-4f40-9355-9bb92e7d1f46.png">

**Comment by ellie** [comment]
Sorry but no - many people share screenshots as part of debugging, and it’s
immensely useful

**Comment by misuzu** [comment]
Does it have to take up the whole line though? Can't it be moved to a corner at the bottom or something like that?

**Comment by ellie** [comment]
I'm not sure how the bottom corner differs to the top corner - either way it's going to take up a line. Sorry about that!

**Comment by misuzu** [comment]
Not necessary. There is already almost empty line which could hold the version:
<img width="229" alt="Знімок екрана 2023-04-16 о 21 13 08" src="https://user-images.githubusercontent.com/248143/232333252-460b7cc0-66fc-492b-9e22-d32c0cea1060.png">

**Comment by ellie** [comment]
It's not going to be empty if someone actually types in it

Sorry, this won't be changing.
