### ISSUE TITLE
Binaries missing in GitHub release

### ISSUE THREAD

**Issue by koterpillar** [ellie/atuin#891]
I am using Atuin via binaries downloaded from the GitHub release, however, they are no longer provided for 14.0.1, seemingly because the [release action](https://github.com/ellie/atuin/actions/runs/4713051719) is now failing.

**Comment by bdavj** [comment]
The refactoring of [cargo.toml](https://github.com/ellie/atuin/commit/c05d2850420a2c163b8f62c33a6cef7c0ae1ad8d#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) (and removal of the name) has caused the workflow to fail here. Would suggest it needs adding back to `workspace.package`.

**Comment by ellie** [comment]
This is sorted now! Sorry for the trouble.
