### ISSUE TITLE
Add a key binding or configuration to run selected command immediately

### ISSUE THREAD

**Issue by cheuk-cheng** [ellie/atuin#906]
I am new to atuin but I had used resh and mcfly before.  Is there a way in autin to run a command in history immediately without pressing <enter> key?  Thanks.

**Comment by VuiMuich** [comment]
This is a duplicate of #78 and I just started looking into this matter with draft PR #907.

**Comment by ellie** [comment]
Closing as a dupe, thanks @VuiMuich

**Comment by VuiMuich** [comment]
> Closing as a dupe, thanks @VuiMuich 

You are very welcome!
