### ISSUE TITLE
Cannot login with: user not found

### ISSUE THREAD

**Issue by stratosgear** [ellie/atuin#936]
Recently migrated to a new machine and trying to resync/login with my old history.

But I get this weird behavior:

```
❯ atuin register -u stratosgear -e my@email.here -p some.random.password.here
Error: username already in use

Location:
    /usr/src/debug/atuin/atuin-14.0.1/atuin-client/src/api_client.rs:50:9

stratos@iocaine 
~ 
❯ atuin login                                                                                               
Please enter username: stratosgear
Please enter encryption key [blank to use existing key file]: 
Please enter password: 
Error: invalid login details: user not found

Location:
    /usr/src/debug/atuin/atuin-14.0.1/atuin-client/src/api_client.rs:84:9
```
I am pretty sure I have the correct password for accessing the account.

So what happened with my username...?  Cannot register and cannot login either...?

Thanks!

**Comment by conradludgate** [comment]
On your other machine, can you run `atuin status` to verify your account info?

If it can't be resolved, you can copy the session file from the old machine over to your new machine

**Comment by stratosgear** [comment]
I do not have access to the old machine... (reinstalled) :(

I am pretty sure my account info is correct because it was tested recently (on the old machine, though) and it worked.

I guess I put too much faith on the online sync server!  It's a shame because I lost a lot of history... :(

**Comment by ellie** [comment]
I’m really sorry but if you can’t login, then your credentials are not
correct. Currently we trust that users look after their creds, but
definitely need some sort of password reset functionality

**Comment by stratosgear** [comment]
You know, thank you!!! 

Your comment about a wrong password, made me check my password again.  I was indeed using the wrong password.

Once I logged in with the "correct" password this time, it worked!

Apologies for the "noise" here....

But again, being able to recover a missed password is something equally important, regardless of the responsibility of the user to safekeep their credentials....

Thanks once again....  I will be closing the issue here!
