### ISSUE TITLE
atuin - will work for ubuntu 16 (or ubun18) - due to libc6 >= 2.29 requirement ?  

### ISSUE THREAD

**Issue by bob454522** [ellie/atuin#944]
I started installing atuin on a few of my systems,  and had no issues on ubuntu 20,  u22 and debian 9.
(im using the suggested:
bash <(curl https://raw.githubusercontent.com/ellie/atuin/main/install.sh)

however once i got to some of our older systems running Ubuntu18 or ubun16 ,  the same install script gave:
 (ubuntu18): The following packages have unmet dependencies:   atuin : Depends: libc6 (>= 2.29) but **2.27-3ubuntu1** is to be installed

 (ubuntu16): The following packages have unmet dependencies:   atuin : Depends: libc6 (>= 2.29) but **2.23-0ubuntu10** is to be installed

I realize there are work-around to force install/update  libc6 >= 2.29 on these older systems (and normally i would just proceed in that direction) - but many replies state this could cause your OS to break (or other apps on it to fail) - **as libc6 , and the specific version used by your specific distro ** is a very frequent dependency for many apps 
ie:
https://askubuntu.com/questions/1143268/how-to-install-a-libc6-version-2-29

**my question is:  is Atuin tested / expected to work on these older OSes ,  or is it ONLY ment for more recent OSes? ** 
If anyone has an experiences please reply -  I understand the risks and that no answer is 100% accurate, just looking for feedback / experiences w atuin on older distro versions

(i understand i could/should update them to latest distros, but these are internal network / closed access VMs and that is not an option in this case.  i do also realize atuin encrypted sends to a cloud server for sync purposes (not relevant to my question here).

thank you!

**Comment by Ngalstyan4** [comment]
I ran into the same issue and managed to work around it by installing via `cargo install atuin`

Make sure a recent rust toolchain is available. I think at least 1.67 is required as[ {integer}::ilog10 ](https://doc.rust-lang.org/stable/std/primitive.i32.html#method.ilog10) is used in the code. I had 1.68
```
rustup install 1.68
rustup default 1.68
cargo install atuin
```

**Comment by bob454522** [comment]
Thank you VERY much!  this helped me get atuin installed on a few older systems (ubuntu 16 , ubuntu 18 and debian 8.11 jessie)!

in the end the exact commands i used/ ran are below-  as a note though, AT FIRST:  `apt install cargo`  , installed a too old version of rust/cargo which then caused `cargo install atuin` to fail, as you had predicted-  thus i had to backtrack, via running:  `apt remove rustc` )

then these are exact commands that worked (after doing above):
 
`curl https://sh.rustup.rs -sSf | sh`
(choose default install)

`source "$HOME/.cargo/env`
(To configure your current shell for rust/cargo, as the installer suggests)

`cargo install atuin`

(took some time, but all ran successfully and i now am running atuin across many of my VMs / systems)  thanks again!
