### ISSUE TITLE
clicking on quickstart link in README opens codespace config

### ISSUE THREAD

**Issue by samdenty** [ellie/atuin#950]
https://user-images.githubusercontent.com/13242392/236691807-a24d0f72-1e76-43e6-9a65-ef72078c9f94.mp4

**Comment by conradludgate** [comment]
Strange. It seems to be a github bug to me. It works fine on my browser and on github mobile

**Comment by ellie** [comment]
Sorry, I can't replicate this either 😞 

Happy to reopen this if someone figures out how we can see the same behaviour
