### ISSUE TITLE
Fuzzier search

### ISSUE THREAD

**Issue by ismith** [ellie/atuin#96]
Right now, the ^r (atuin search -i) behavior searches for strings with matching prefixes; I'd like it to search for substrings.

Ie, `terr` should match both `terraform plan` and `git commit -a -m '[terraform] do the thing'`.

**Comment by conradludgate** [comment]
Do you mean something like #75? New release should be soon :)

**Comment by ismith** [comment]
:awwyiss: I do, thanks!

**Comment by ellie** [comment]
I was actually going to get a release out earlier this evening, but then I found https://github.com/ellie/atuin/pull/95. Now it's a little late + I'd rather not push an update right before I go to bed ahaha. Should be good tomorrow!

**Comment by ismith** [comment]
No rush, this issue was as much a placeholder for me to start looking as anything else :laughing:

**Comment by Dentrax** [comment]
Not sure if this is correct issue to ask but:

Currently, I'm able to substring search by adding `*` prefix before the search keyword. How can I make substring search default mode? Default behavior of <kbd>CTRL+R</kbd> is applying _prefix_ search, which is a bit non-effective for me.

@ismith @ellie 🙏

**Comment by azzamsa** [comment]
@Dentrax take a look at https://github.com/ellie/atuin/blob/main/docs/config.md#search_mode
