### ISSUE TITLE
Feature request: sync and better search with readline ui

### ISSUE THREAD

**Issue by jbellis** [ellie/atuin#964]
Thanks for the cool project!  New user from HN here.

Even with a 1-line display set, I find it distracting to have my point-of-attention jump around with atuin.  Could you add an option to leave ctrl-r and arrow keys behaving like normal readline does (i.e. pulling the top result into my current terminal's prompt), and just feed better results to it?

**Comment by ellie** [comment]
Hey! Thank you for the kind words

There are a few scripts people have written that we need to centralise, but honestly that isn't really something we will be implementing any time soon. 

I personally find the normal readline experience to be terrible, which is why I made this :)
