### ISSUE TITLE
Can't register - MacOS

### ISSUE THREAD

**Issue by slipcon** [ellie/atuin#968]
After entering a password for `atuin register` I get:

Error: builder error: The Trust Settings Record was corrupted.

Caused by:
    The Trust Settings Record was corrupted.

Location:
    /private/tmp/atuin-20230416-6391-1u26z52/atuin-14.0.1/atuin-client/src/api_client.rs:47:16
    
    
    any suggestions for things to try?

**Comment by ellie** [comment]
Yikes. I think something is messed up with your local mac certificate keychain. Probs some corrupt or expired certs in there - worth checking

**Comment by slipcon** [comment]
i went in to Keychain Access and deleted a bunch of expired certs - but I don't see anything that indicates corruption.  No change in atuin register -  any hints how to debug which certificate might be an issue?

**Comment by slipcon** [comment]
I found this, which sort of pointed me at any untrusted certs in the keychain access:

https://github.com/cloudflare/wrangler-legacy/issues/1656

I found one for an old firewall we had at work which must have had a self-signed CA -  i deleted it, and all worked.   Strange!
