### ISSUE TITLE
zsh multiline import broken

### ISSUE THREAD

**Issue by conradludgate** [ellie/atuin#98]
I entered `echo \<NEWLINE>bar` into my zsh terminal, and the resulting `~/.zsh_history` entry contained the lines

```
: 1620636746:0;echo \\
bar
```

With two `\` tokens. The current import isn't taking this into account. The command is saved with both `\\` characters and is interpreted differently.

This possibly impacts bash import too.

Note, any new entries don't have this issue. This is only for import

**Comment by dbaynard** [comment]
I've been bitten by this, and worked around it with a hacky solution. It replaces every slash followed by a newline with _just_ the newline. It is not idempotent, and will cause damage if run more than once.

```zsh
sqlite3 --box ~/.local/share/atuin/history.db <<- 'SQL'
begin;
update history
   set command = replace(command, '\' || X'0A', X'0A')
 where command like '%\' || X'0A' || '%'
;
select changes();
rollback;
SQL
```

Change the `rollback` to `commit` to make the changes stick. I then had to reload zsh.
